const IDF780 = [{"id":"I-1","side":"b","board":"bbbbbbbbbbbb....w....wwwwwwwwwww","moves":"ab4"},
{"id":"I-2","side":"w","board":"bbbbbbbb.bbbb...w....wwwwwwwwwww","moves":"ab4 ba5"},
{"id":"I-3","side":"w","board":"bbbb.bbbbbbbb...w...wwww.wwwwwww","moves":"ab4 ba5 ba3 ab6"},
{"id":"I-4","side":"w","board":"bbbb.bbbb.bbbb..w...wwwwwwww.www","moves":"ab4 ba5 ba3 ab6 ab2 dc5"},
{"id":"I-5","side":"w","board":"bbbbb.bb.bbbbb..w...wwwwwwww.www","moves":"ab4 ba5 ba3 cb6 ab2 bc5"},
{"id":"I-6","side":"w","board":"bbbb.bbbb.bbb.b.w.w.www..wwwwwww","moves":"ab4 ba5 ba3 ab6 gf4 de5"},
{"id":"I-7","side":"w","board":"bbbbb.bbb.bbb.b.w...wwwwwwwww.ww","moves":"ab4 ba5 ba3 cb6 cb2 de5"},
{"id":"I-8","side":"w","board":".bbbbbbbbbbbb...w.w.ww.w.wwwwwww","moves":"ab4 ba5 ba3 cb6 ef4 bc7"},
{"id":"I-9","side":"w","board":"bbbbb.bbbb.bb..bw.w.ww.w.wwwwwww","moves":"ab4 ba5 ba3 cb6 ef4 fg5"},
{"id":"I-10","side":"b","board":"bbbbb.bbbbbbb...w.w.www..wwwwwww","moves":"ab4 ba5 ba3 cb6 gf4"},
{"id":"I-11","side":"w","board":"bbbbb.bbbb.bb.b.w..wwww..wwwwwww","moves":"ab4 ba5 ba3 cb6 gh4 fe5"},
{"id":"I-12","side":"w","board":"bbbbbbbb..bbb.b.w...wwww.wwwwwww","moves":"ab4 ba5 ba3 de5"},
{"id":"I-13","side":"b","board":"bbbbbbbb.b.bb.b.w..wwww..wwwwwww","moves":"ab4 ba5 ba3 fe5 gh4"},
{"id":"I-14","side":"w","board":"bbbb.bbbb.bbbb..ww...wwww.wwwwww","moves":"ab4 ba5 ed4 ab6 de3 dc5"},
{"id":"I-15","side":"w","board":".bbbbbbbbbbbb...ww...wwwww.wwwww","moves":"ab4 ba5 ed4 ab6 fe3 ba7"},
{"id":"I-16","side":"w","board":"bbbb.bbbb.bbbb..ww...wwwww.wwwww","moves":"ab4 ba5 ed4 ab6 fe3 dc5"},
{"id":"I-17","side":"w","board":"bbbb.bbbbb.bb.b.ww...wwwww.wwwww","moves":"ab4 ba5 ed4 ab6 fe3 fe5"},
{"id":"I-18","side":"w","board":"bbbb.bbbbbb.b..bww...wwwww.wwwww","moves":"ab4 ba5 ed4 ab6 fe3 hg5"},
{"id":"I-19","side":"w","board":"bbbbb.bbbbbbb...ww...w.wwwwwwwww","moves":"ab4 ba5 ed4 cb6"},
{"id":"I-20","side":"w","board":"bbbbbbbb..bbbb..ww...w.wwwwwwwww","moves":"ab4 ba5 ed4 dc5"},
{"id":"I-21","side":"w","board":"bbbbb.bb..bbb.b..w...w.wwwwwwwww","moves":"ab4 ba5 ed4 dc5 bd6 ce5"},
{"id":"I-22","side":"w","board":"bbbbbbb..b.bb.b.w....w.wwwwwwwww","moves":"ab4 ba5 ed4 fe5 df6 ge5"},
{"id":"I-23","side":"w","board":"bbbbbb.b.b.bb..bw....w.wwwwwwwww","moves":"ab4 ba5 ed4 fe5 df6 eg5"},
{"id":"I-24","side":"w","board":"bbbbbbbb..bbb...wwbw.w..wwwwwwww","moves":"ab4 ba5 ed4 de5 gh4 ef4"},
{"id":"I-25","side":"w","board":"bbbbbbbb.b.bb..bww...w.wwwwwwwww","moves":"ab4 ba5 ed4 fg5"},
{"id":"I-26","side":"w","board":"bbbbbbbb.bb.b..bww...w.wwwwwwwww","moves":"ab4 ba5 ed4 hg5"},
{"id":"II-1","side":"w","board":"bbbbbbbbbbbbw.......wwwwwwww.www","moves":"a1-a5"},
{"id":"II-2","side":"w","board":"bbbb.bbbbbbbw......bwwwwwwww.www","moves":"a1-a5 a7-h4"},
{"id":"II-3","side":"w","board":"bbbbbbbb.bbbw..b....wwwwwwww.www","moves":"a1-a5 b6-g5"},
{"id":"II-4","side":"w","board":"bbbbbbbb.bbbw......bwwwwwwww.www","moves":"a1-a5 b6-h4"},
{"id":"II-5","side":"w","board":"bbbbbbbbb.bbw.b.....wwwwwwww.www","moves":"a1-a5 d6-e5"},
{"id":"II-6","side":"w","board":"bbbbbbbbbb.bw......bwwwwwwww.www","moves":"a1-a5 f6-h4"},
{"id":"II-7","side":"w","board":"bbbbbbb.bbbbw...b...wwwwwwww.www","moves":"a1-a5 g7-b4"},
{"id":"II-8","side":"w","board":"bbbbbbb.bbbbw.b.....wwwwwwww.www","moves":"a1-a5 g7-e5"},
{"id":"II-9","side":"w","board":"bbbbbbb.bbbbw..b....wwwwwwww.www","moves":"a1-a5 g7-g5"},
{"id":"II-10","side":"w","board":"bbbbbbb.bbbbw......bwwwwwwww.www","moves":"a1-a5 g7-h4"},
{"id":"II-11","side":"w","board":"bbb.bbbbbbbbw..b....wwwwwwww.www","moves":"a1-a5 h8-g5"},
{"id":"II-12","side":"w","board":"bbbbbbbbbbb.w...b...wwwwwwww.www","moves":"a1-a5 h6-b4"},
{"id":"II-13","side":"w","board":"bbbb.bbbbbbbb...w...wwwwwwww.www","moves":"a1-b4 a7-a5"},
{"id":"II-14","side":"w","board":"bbbb.bbbbbbb...bw...wwwwwwww.www","moves":"a1-b4 a7-g5"},
{"id":"II-15","side":"w","board":"bbbbbbbb.bbbb...w...wwwwwwww.www","moves":"a1-b4 b6-a5"},
{"id":"II-16","side":"w","board":"bbbbbbbbb.bb.b..w...wwwwwwww.www","moves":"a1-b4 d6-c5"},
{"id":"II-17","side":"w","board":"bbbbbbbbb.bb...bw...wwwwwwww.www","moves":"a1-b4 d6-g5"},
{"id":"II-18","side":"w","board":"bbb.bbbbbbbb..b.w...wwwwwwww.www","moves":"a1-b4 h8-e5"},
{"id":"II-19","side":"w","board":"bbbbbbbbbbb....bw...wwwwwwww.www","moves":"a1-b4 h6-g5"},
{"id":"II-20","side":"w","board":"bbbb.bbbbbbb.b...w..wwwwwwww.www","moves":"a1-d4 a7-c5"},
{"id":"II-21","side":"w","board":"bbbb.bbbbbbb.....wb.wwwwwwww.www","moves":"a1-d4 a7-f4"},
{"id":"II-22","side":"w","board":"bbbbbbbb.bbbb....w..wwwwwwww.www","moves":"a1-d4 b6-a5"},
{"id":"II-23","side":"w","board":"bbbbbbbb.bbb.b...w..wwwwwwww.www","moves":"a1-d4 b6-c5"},
{"id":"II-24","side":"w","board":"bbbb.bbbbbbbw.......bwwwwwwwwwww","moves":"a3-a5 a7-a3"},
{"id":"II-25","side":"w","board":"bbbbbbbb.bbbw.......bwwwwwwwwwww","moves":"a3-a5 b6-a3"},
{"id":"II-26","side":"w","board":"bbbbbbbbb.bbw...b....wwwwwwwwwww","moves":"a3-a5 d6-b4"},
{"id":"III-1","side":"b","board":"bbbbbbbb.b.bb.b.w..w.wwwwww.wwww","moves":"ab4 ba5 gh4 fe5 hg3"},
{"id":"III-2","side":"w","board":"bbbbbbbb.b.bb..bw..w.ww.wwwwwwww","moves":"ab4 ba5 gh4 fg5"},
{"id":"III-3","side":"w","board":"bbbbbbbb.bbb.b..w....wwwwwwwwwww","moves":"ab4 bc5"},
{"id":"III-4","side":"w","board":"bbbbbbbb.bbbw...b....wwwwwwwwwww","moves":"ab4 bc5 ba5 cb4"},
{"id":"III-5","side":"w","board":"bbbbbbbb.b.bw.b.bw...w.wwwwwwwww","moves":"ab4 bc5 ba5 cb4 ed4 fe5"},
{"id":"III-6","side":"w","board":"bbbbbbbb.b.bw..bbw...w.wwwwwwwww","moves":"ab4 bc5 ba5 cb4 ed4 fg5"},
{"id":"III-7","side":"w","board":"bbbbbbbb.bb.w..bbw...w.wwwwwwwww","moves":"ab4 bc5 ba5 cb4 ed4 hg5"},
{"id":"III-8","side":"w","board":"bbbbbbbb.b.bw.b.b.w..ww.wwwwwwww","moves":"ab4 bc5 ba5 cb4 gf4 fe5"},
{"id":"III-9","side":"b","board":"bbbbbbbb.bbbw...b..w.ww.wwwwwwww","moves":"ab4 bc5 ba5 cb4 gh4"},
{"id":"III-10","side":"b","board":"bbbbbbbb.b.bwb.b..w..w.wwwwwwwww","moves":"ab4 bc5 ba5 fg5 ef4"},
{"id":"III-11","side":"w","board":"bbbbbbbb.b.bwb.b.....wwwwwwwwwww","moves":"ab4 bc5 ba5 fg5"},
{"id":"III-12","side":"w","board":"bbbbbbbbb.bb.b..w....wwwwwwwwwww","moves":"ab4 dc5"},
{"id":"III-13","side":"b","board":"bbbbbb.bb.bb.b.....w.ww.wwwwwwww","moves":"ab4 dc5 bd6 ec5 gh4"},
{"id":"III-14","side":"b","board":"bbbbb.bbb.bb..b...w..w.wwwwwwwww","moves":"ab4 dc5 bd6 ce5 ef4"},
{"id":"III-15","side":"w","board":"bbbbbbbbb.bb..b.w....wwwwwwwwwww","moves":"ab4 de5"},
{"id":"III-16","side":"b","board":"bbbbbbbbb..bw.bb..w..w.wwwwwwwww","moves":"ab4 de5 ba5 fg5 ef4"},
{"id":"III-17","side":"b","board":"bbbbbbbbb..bw.bb...w.ww.wwwwwwww","moves":"ab4 de5 ba5 fg5 gh4"},
{"id":"III-18","side":"w","board":"bbbbbbbbb..b..bbw...wwww.wwwwwww","moves":"ab4 de5 ba3 fg5"},
{"id":"III-19","side":"b","board":"bbbbbbbbb..b..bbw.w.www..wwwwwww","moves":"ab4 de5 ba3 fg5 gf4"},
{"id":"III-20","side":"b","board":"bbbbbbbbb.b.w.bb.w...w.wwwwwwwww","moves":"ab4 de5 ed4 hg5 ba5"},
{"id":"III-21","side":"b","board":"bbbbbbbbb.bb..b.w..w.ww.wwwwwwww","moves":"ab4 de5 gh4"},
{"id":"III-22","side":"w","board":"bbbbbbbbbb.b..b.w....wwwwwwwwwww","moves":"ab4 fe5"},
{"id":"III-23","side":"w","board":"bbbbbbbbbb.bw.....b..wwwwwwwwwww","moves":"ab4 fe5 ba5 ef4"},
{"id":"III-24","side":"w","board":"bbbbbbb.bbbbw.b......wwwwwwwwwww","moves":"ab4 fe5 ba5 gf6"},
{"id":"III-25","side":"w","board":"bbbbbbbbb..b..b.b....wwwwwwwwwww","moves":"ab4 fe5 bc5 db4"},
{"id":"III-26","side":"b","board":"bbbbbbbbbb.b..b.w.w..w.wwwwwwwww","moves":"ab4 fe5 ef4"},
{"id":"IV-1","side":"w","board":"bbbbbbbbbb.bw.......bwwwwwwwwwww","moves":"a3-a5 f6-a3"},
{"id":"IV-2","side":"w","board":"bbbbbbbbbbb.w.......bwwwwwwwwwww","moves":"a3-a5 h6-a3"},
{"id":"IV-3","side":"w","board":"bbbbbbbbbbb.w...b....wwwwwwwwwww","moves":"a3-a5 h6-b4"},
{"id":"IV-4","side":"w","board":"bbbbbbbbbbb.w.b......wwwwwwwwwww","moves":"a3-a5 h6-e5"},
{"id":"IV-5","side":"w","board":"bbbbbbbb.bbb....w...bwwwwwwwwwww","moves":"a3-b4 b6-a3"},
{"id":"IV-6","side":"w","board":"bbbbbbbbb.bb....w...bwwwwwwwwwww","moves":"a3-b4 d6-a3"},
{"id":"IV-7","side":"w","board":"bbbbbb.bbbbbb...w....wwwwwwwwwww","moves":"a3-b4 e7-a5"},
{"id":"IV-8","side":"w","board":"bbbbbbbbbbb.....w...bwwwwwwwwwww","moves":"a3-b4 h6-a3"},
{"id":"IV-9","side":"w","board":"bbbbbbbbbbb...b.w....wwwwwwwwwww","moves":"a3-b4 h6-e5"},
{"id":"IV-10","side":"w","board":"bbb.bbbbbbbb....w...bwwwwwwwwwww","moves":"a3-b4 h8-a3"},
{"id":"IV-11","side":"w","board":"bbbbbbbb.bbb.w......bwwwwwwwwwww","moves":"a3-c5 b6-a3"},
{"id":"IV-12","side":"w","board":"bbbbbbbbb.bb.w......bwwwwwwwwwww","moves":"a3-c5 d6-a3"},
{"id":"IV-13","side":"w","board":"bbbbbbbbbb.b.w......bwwwwwwwwwww","moves":"a3-c5 f6-a3"},
{"id":"IV-14","side":"w","board":"bbbbbbb.bbbb.w......bwwwwwwwwwww","moves":"a3-c5 g7-a3"},
{"id":"IV-15","side":"w","board":"bbb.bbbbbbbb.w......bwwwwwwwwwww","moves":"a3-c5 h8-a3"},
{"id":"IV-16","side":"w","board":"bbbbbbbb.bbb.....w..bwwwwwwwwwww","moves":"a3-d4 b6-a3"},
{"id":"IV-17","side":"w","board":"bbbbb.bbbbbbb....w...wwwwwwwwwww","moves":"a3-d4 c7-a5"},
{"id":"IV-18","side":"w","board":"bbbbbb.bbbbb.b...w...wwwwwwwwwww","moves":"a3-d4 e7-c5"},
{"id":"IV-19","side":"w","board":"bbbbbbbbbb.b.....w..bwwwwwwwwwww","moves":"a3-d4 f6-a3"},
{"id":"IV-20","side":"w","board":"bbbbbbb.bbbb.....w..bwwwwwwwwwww","moves":"a3-d4 g7-a3"},
{"id":"IV-21","side":"w","board":"bbbbbbb.bbbbb....w...wwwwwwwwwww","moves":"a3-d4 g7-a5"},
{"id":"IV-22","side":"w","board":"bbb.bbbbbbbb.....w..bwwwwwwwwwww","moves":"a3-d4 h8-a3"},
{"id":"IV-23","side":"w","board":"bbb.bbbbbbbb.....w.b.wwwwwwwwwww","moves":"a3-d4 h8-h4"},
{"id":"IV-24","side":"w","board":"bbbbbbbbbbb....b.w...wwwwwwwwwww","moves":"a3-d4 h6-g5"},
{"id":"IV-25","side":"w","board":"bbbb.bbbbbbb.bw......wwwwwwwwwww","moves":"a3-e5 a7-c5"},
{"id":"IV-26","side":"w","board":"bbbbbbbb.bbb..w.....bwwwwwwwwwww","moves":"a3-e5 b6-a3"},
{"id":"V-1","side":"w","board":"bbbbbbb.bbbb..b.w..w.ww.wwwwwwww","moves":"ab4 fe5 gh4 gf6"},
{"id":"V-2","side":"b","board":"bbbbbbb.bbbb..b.w..w.wwwww.wwwww","moves":"ab4 fe5 gh4 gf6 fg3"},
{"id":"V-3","side":"w","board":"bbbbbbbbbb.b...bw....wwwwwwwwwww","moves":"ab4 fg5"},
{"id":"V-4","side":"b","board":"bbbbbbb.bbbbw..b.w...w.wwwwwwwww","moves":"ab4 fg5 ba5 gf6 ed4"},
{"id":"V-5","side":"b","board":"bbbbbb.bbbbb...bww..ww.w.wwwwwww","moves":"ab4 fg5 ba3 ef6 ed4"},
{"id":"V-6","side":"w","board":"bbbbbbbbb..b...bb....wwwwwwwwwww","moves":"ab4 fg5 bc5 db4"},
{"id":"V-7","side":"w","board":"bbbbbbbbbbb....bw....wwwwwwwwwww","moves":"ab4 hg5"},
{"id":"V-8","side":"w","board":"bbbbbbbbbbb.....w.b.wwww.wwwwwww","moves":"ab4 hg5 ba3 gf4"},
{"id":"V-9","side":"w","board":"bbbbbbbb.bb..b.bw.w..ww.wwwwwwww","moves":"ab4 hg5 gf4 bc5"},
{"id":"V-10","side":"w","board":"bbbbbbb.bbbb...bw.w..ww.wwwwwwww","moves":"ab4 hg5 gf4 gh6"},
{"id":"V-11","side":"w","board":"bbbbbbbb.bb.b..bw..w.ww.wwwwwwww","moves":"ab4 hg5 gh4 ba5"},
{"id":"V-12","side":"w","board":"bbbbbbbbbbb.....w.bw.ww.wwwwwwww","moves":"ab4 hg5 gh4 gf4"},
{"id":"V-13","side":"b","board":"bbbbbbbbbbbb....w...w.wwwwwwwwww","moves":"cb4"},
{"id":"V-14","side":"w","board":"bbbbb.bbb.bbbw........wwwwwwwwww","moves":"cb4 ba5 bc5 db4 ac5 cb6"},
{"id":"V-15","side":"w","board":"bbbbbbbb...bbwb.......wwwwwwwwww","moves":"cb4 ba5 bc5 db4 ac5 fe5"},
{"id":"V-16","side":"w","board":"bbbbb.bbbb.bb.b.w..wwww.w.wwwwww","moves":"cb4 ba5 dc3 fe5 gh4 cb6"},
{"id":"V-17","side":"w","board":"bbbbbbbb.bb.b..bw...wwwww.wwwwww","moves":"cb4 ba5 dc3 hg5"},
{"id":"V-18","side":"b","board":"bbbbbbbb.bbbb...w.w.w..wwwwwwwww","moves":"cb4 ba5 ef4"},
{"id":"V-19","side":"b","board":"bbbbbbbb.bbbb...w.w.w.w.wwwwwwww","moves":"cb4 ba5 gf4"},
{"id":"V-20","side":"b","board":"bbbbbbbb.bbb.....ww.w..w.wwwwwww","moves":"cb4 ba5 ef4 ac3 bd4"},
{"id":"V-21","side":"b","board":"bbbbbbbb.bbbb...w..ww.w.wwwwwwww","moves":"cb4 ba5 gh4"},
{"id":"V-22","side":"w","board":"bbbbbbbb..bb..b..w.ww.w..wwwwwww","moves":"cb4 ba5 gh4 ac3 bd4 de5"},
{"id":"V-23","side":"w","board":"bbbbbbbb.bbb.b..w...w.wwwwwwwwww","moves":"cb4 bc5"},
{"id":"V-24","side":"b","board":"bbbbbbbb.b.b.bb.ww..ww.w.wwwwwww","moves":"cb4 bc5 bc3 fe5 ed4"},
{"id":"V-25","side":"w","board":"bbbb.bbbbb.b.b.bww..w.ww.wwwwwww","moves":"cb4 bc5 bc3 fg5 cd4 ab6"},
{"id":"V-26","side":"b","board":"bbbbbbbb.b.b.b.bww..ww.w.wwwwwww","moves":"cb4 bc5 bc3 fg5 ed4"},
{"id":"VI-1","side":"w","board":"bbbbbbb.bbbb..w.....bwwwwwwwwwww","moves":"a3-e5 g7-a3"},
{"id":"VI-2","side":"w","board":"bbbbbbb.bbbb..w....b.wwwwwwwwwww","moves":"a3-e5 g7-h4"},
{"id":"VI-3","side":"w","board":"bbb.bbbbbbbb..w.....bwwwwwwwwwww","moves":"a3-e5 h8-a3"},
{"id":"VI-4","side":"w","board":"bbbbbbbbbbbb......w..wwwwwwwwwww","moves":"a3-f4 ---"},
{"id":"VI-5","side":"w","board":"bbbb.bbbbbbb.b....w..wwwwwwwwwww","moves":"a3-f4 a7-c5"},
{"id":"VI-6","side":"w","board":"bbbbb.bbbbbb.b....w..wwwwwwwwwww","moves":"a3-f4 c7-c5"},
{"id":"VI-7","side":"w","board":"bbbbbbbbbb.b..b...w..wwwwwwwwwww","moves":"a3-f4 f6-e5"},
{"id":"VI-8","side":"w","board":"bbbb.bbbbbbb...w....bwwwwwwwwwww","moves":"a3-g5 a7-a3"},
{"id":"VI-9","side":"w","board":"bbbbbbbb.bbb...w....bwwwwwwwwwww","moves":"a3-g5 b6-a3"},
{"id":"VI-10","side":"w","board":"bbbbb.bbbbbb...w....bwwwwwwwwwww","moves":"a3-g5 c7-a3"},
{"id":"VI-11","side":"w","board":"bbbbbbbbb.bb...w....bwwwwwwwwwww","moves":"a3-g5 d6-a3"},
{"id":"VI-12","side":"w","board":"bbbbbbbbb.bb.b.w.....wwwwwwwwwww","moves":"a3-g5 d6-c5"},
{"id":"VI-13","side":"w","board":"bbbbbbbbbb.b...w....bwwwwwwwwwww","moves":"a3-g5 f6-a3"},
{"id":"VI-14","side":"w","board":"bbbbbbb.bbbb...w....bwwwwwwwwwww","moves":"a3-g5 g7-a3"},
{"id":"VI-15","side":"w","board":"bbb.bbbbbbbb...w....bwwwwwwwwwww","moves":"a3-g5 h8-a3"},
{"id":"VI-16","side":"w","board":"bbbb.bbbbbbb.......wbwwwwwwwwwww","moves":"a3-h4 a7-a3"},
{"id":"VI-17","side":"w","board":"bbbb.bbbbbbbb......w.wwwwwwwwwww","moves":"a3-h4 a7-a5"},
{"id":"VI-18","side":"w","board":"bbbbbbbb.bbb.b.....w.wwwwwwwwwww","moves":"a3-h4 b6-c5"},
{"id":"VI-19","side":"w","board":"bbbbb.bbbbbb.......wbwwwwwwwwwww","moves":"a3-h4 c7-a3"},
{"id":"VI-20","side":"w","board":"bbbbbbbbb.bb.......wbwwwwwwwwwww","moves":"a3-h4 d6-a3"},
{"id":"VI-21","side":"w","board":"bbbbbbbbb.bb.b.....w.wwwwwwwwwww","moves":"a3-h4 d6-c5"},
{"id":"VI-22","side":"w","board":"bbbbbbbbb.bb..b....w.wwwwwwwwwww","moves":"a3-h4 d6-e5"},
{"id":"VI-23","side":"w","board":"bbbbbb.bbbbb.......wbwwwwwwwwwww","moves":"a3-h4 e7-a3"},
{"id":"VI-24","side":"w","board":"bbbbbb.bbbbbb......w.wwwwwwwwwww","moves":"a3-h4 e7-a5"},
{"id":"VI-25","side":"w","board":"bbbbbbbbbb.b.......wbwwwwwwwwwww","moves":"a3-h4 f6-a3"},
{"id":"VI-26","side":"w","board":"bbbbbbbbbb.b.b.....w.wwwwwwwwwww","moves":"a3-h4 f6-c5"},
{"id":"VII-1","side":"w","board":"bbbb.bbbbbbb.b..w...wwwww.wwwwww","moves":"cb4 bc5 dc3 ab6"},
{"id":"VII-2","side":"w","board":"bbbbbbbb.b.b.bb.w...wwwww.wwwwww","moves":"cb4 bc5 dc3 fe5"},
{"id":"VII-3","side":"w","board":"bbbbbb.b.bbb.bb.w.w.ww.ww.wwwwww","moves":"cb4 bc5 dc3 fe5 ef4 ef6"},
{"id":"VII-4","side":"w","board":"bbbb.bbbbb.b.bb.w..wwww.w.wwwwww","moves":"cb4 bc5 dc3 fe5 gh4 ab6"},
{"id":"VII-5","side":"w","board":"bbbbbbb..bbb.bb.w..wwww.w.wwwwww","moves":"cb4 bc5 dc3 fe5 gh4 gf6"},
{"id":"VII-6","side":"w","board":"bbbbb.bbbbbb....ww..w..www.wwwww","moves":"cb4 bc5 ed4 ce3 fd4 cb6"},
{"id":"VII-7","side":"w","board":"bbbbbbbb..bb..b.ww..w..www.wwwww","moves":"cb4 bc5 ed4 ce3 fd4 de5"},
{"id":"VII-8","side":"w","board":"bbbb.bbbbb.b.b.bw.w.w.wwwww.wwww","moves":"cb4 bc5 gf4 ab6 hg3 fg5"},
{"id":"VII-9","side":"w","board":"bbbbbbbbb.bb.b..w...w.wwwwwwwwww","moves":"cb4 dc5"},
{"id":"VII-10","side":"w","board":"bbbbbb.b..bbbb....w.w.w.wwwwwwww","moves":"cb4 dc5 bd6 ec5 gf4 ba5"},
{"id":"VII-11","side":"w","board":"bbbbb.bb..bbb.b....ww.w.wwwwwwww","moves":"cb4 dc5 bd6 ce5 gh4 ba5"},
{"id":"VII-12","side":"w","board":"bbbbbbbbb.bb..b.w...w.wwwwwwwwww","moves":"cb4 de5"},
{"id":"VII-13","side":"w","board":"bbbbbbbb..bbwbb.....w.wwwwwwwwww","moves":"cb4 de5 ba5 bc5"},
{"id":"VII-14","side":"w","board":"bbbbbbbbb..bw.bb....w.wwwwwwwwww","moves":"cb4 de5 ba5 fg5"},
{"id":"VII-15","side":"w","board":"bbbbbbbbb..b..bbw...wwwww.wwwwww","moves":"cb4 de5 dc3 fg5"},
{"id":"VII-16","side":"w","board":"bbbbbbbb..bbb.b.w.w.w..wwwwwwwww","moves":"cb4 de5 ef4 ba5"},
{"id":"VII-17","side":"b","board":"bbbbbbbbb.bb..b.w.w.w.w.wwwwwwww","moves":"cb4 de5 gf4"},
{"id":"VII-18","side":"w","board":"bbbbbbbbb..b..b.w.w.w.w.www.wwww","moves":"cb4 de5 gf4 eg3 hf4 fe5"},
{"id":"VII-19","side":"w","board":"bbbbb.bbbbbb..b.w..ww.w.wwwwwwww","moves":"cb4 de5 gh4 cd6"},
{"id":"VII-20","side":"w","board":"bbbbbbbb.b.bwbb.....w.wwwwwwwwww","moves":"cb4 fe5 ba5 bc5"},
{"id":"VII-21","side":"b","board":"bbbbbbb.bbbb..b.w...wwwwwwww.www","moves":"cb4 fe5 bc3 gf6 ab2"},
{"id":"VII-22","side":"w","board":"bbbbbbb.bb.b..bbw...wwwwwwwww.ww","moves":"cb4 fe5 bc3 gf6 cb2 fg5"},
{"id":"VII-23","side":"b","board":"bbbbbbb.bbbb..b.ww..ww.w.wwwwwww","moves":"cb4 fe5 bc3 gf6 ed4"},
{"id":"VII-24","side":"w","board":"bbb.bbbbbbbb..b.w..wwww..wwwwwww","moves":"cb4 fe5 bc3 gf6 gh4 hg7"},
{"id":"VII-25","side":"w","board":"bbbbbbb.bbbb..b.w...wwwww.wwwwww","moves":"cb4 fe5 dc3 gf6"},
{"id":"VII-26","side":"w","board":"bbbbbbbb.b.bb.b.w.w.w..wwwwwwwww","moves":"cb4 fe5 ef4 ba5"},
{"id":"VIII-1","side":"w","board":"bbbbbbbbbb.b..b....w.wwwwwwwwwww","moves":"a3-h4 f6-e5"},
{"id":"VIII-2","side":"w","board":"bbbbbbb.bbbb.......wbwwwwwwwwwww","moves":"a3-h4 g7-a3"},
{"id":"VIII-3","side":"w","board":"bbbbbbb.bbbbb......w.wwwwwwwwwww","moves":"a3-h4 g7-a5"},
{"id":"VIII-4","side":"w","board":"bbbbbbb.bbbb.b.....w.wwwwwwwwwww","moves":"a3-h4 g7-c5"},
{"id":"VIII-5","side":"w","board":"bbbbbbb.bbbb..b....w.wwwwwwwwwww","moves":"a3-h4 g7-e5"},
{"id":"VIII-6","side":"w","board":"bbbbbbbbbbb........wbwwwwwwwwwww","moves":"a3-h4 h6-a3"},
{"id":"VIII-7","side":"w","board":"bbbbbbbbbbb.b......w.wwwwwwwwwww","moves":"a3-h4 h6-a5"},
{"id":"VIII-8","side":"w","board":"bbbbbbbbbbbw.b.......wwwwwwwwwww","moves":"a3-h6 h6-c5"},
{"id":"VIII-9","side":"w","board":"bbbb.bbbbbbbb.......wwwwwwwwwwww","moves":"--- a7-a5"},
{"id":"VIII-10","side":"w","board":"bbbb.bbbbbbb.b......wwwwwwwwwwww","moves":"--- a7-c5"},
{"id":"VIII-11","side":"w","board":"bbbb.bbbbbbb...b....wwwwwwwwwwww","moves":"--- a7-g5"},
{"id":"VIII-12","side":"w","board":"bbbb.bbbbbbb.......bwwwwwwwwwwww","moves":"--- a7-h4"},
{"id":"VIII-13","side":"w","board":"bbbbbbbbbbbbw.......wwww.wwwwwww","moves":"b2-a5 ---"},
{"id":"VIII-14","side":"w","board":"bbbb.bbbbbbbw.b.....wwww.wwwwwww","moves":"b2-a5 a7-e5"},
{"id":"VIII-15","side":"w","board":"bbbb.bbbbbbbw......bwwww.wwwwwww","moves":"b2-a5 a7-h4"},
{"id":"VIII-16","side":"w","board":"bbbbbbbb.bbbw...b...wwww.wwwwwww","moves":"b2-a5 b6-b4"},
{"id":"VIII-17","side":"w","board":"bbbbbbbbbb.bw.b.....wwww.wwwwwww","moves":"b2-a5 f6-e5"},
{"id":"VIII-18","side":"w","board":"bbbbbbbbbbb.w..b....wwww.wwwwwww","moves":"b2-a5 h6-g5"},
{"id":"VIII-19","side":"w","board":"bbbbbbbbb.bb..b.w...wwww.wwwwwww","moves":"b2-b4 d6-e5"},
{"id":"VIII-20","side":"w","board":"bbbbbbbbb.bb...bw...wwww.wwwwwww","moves":"b2-b4 d6-g5"},
{"id":"VIII-21","side":"w","board":"bbb.bbbbbbbbb...w...wwww.wwwwwww","moves":"b2-b4 h8-a5"},
{"id":"VIII-22","side":"w","board":"bbbbbbbbbbb...b.w...wwww.wwwwwww","moves":"b2-b4 h6-e5"},
{"id":"VIII-23","side":"w","board":"bbbbbbbbbbbb.w......wwww.wwwwwww","moves":"b2-c5 ---"},
{"id":"VIII-24","side":"w","board":"bbbbbbb.bbbb.w.b....wwww.wwwwwww","moves":"b2-c5 g7-g5"},
{"id":"VIII-25","side":"w","board":"bbbbbbbbbbbb.....w..wwww.wwwwwww","moves":"b2-d4 ---"},
{"id":"VIII-26","side":"w","board":"bbbb.bbbbbbb...b.w..wwww.wwwwwww","moves":"b2-d4 a7-g5"},
{"id":"IX-1","side":"b","board":"bbbbbbbb.b.bbwb...w.w..wwwwwwwww","moves":"cb4 fe5 ef4 ba5 bc5"},
{"id":"IX-2","side":"b","board":"bbbbbbb.bbbb..b.w.w.ww.w.wwwwwww","moves":"cb4 fe5 ef4 gf6 bc3"},
{"id":"IX-3","side":"w","board":"bbbbbbb..bbb.bb.w.w.w.www.wwwwww","moves":"cb4 fe5 ef4 gf6 de3 bc5"},
{"id":"IX-4","side":"b","board":"bbbbbbbb.b.bb.bww...w.w.wwwwwwww","moves":"cb4 fe5 gh4 ba5 hg5"},
{"id":"IX-5","side":"b","board":"bbbbbbbb.b.b.bbww...w.w.wwwwwwww","moves":"cb4 fe5 gh4 bc5 hg5"},
{"id":"IX-6","side":"w","board":"bbbbbbbb.b.bb..bww..w..wwwwwwwww","moves":"cb4 fg5 ed4 ba5"},
{"id":"IX-7","side":"w","board":"bbbbbbbbb..b.b.bww..w..wwwwwwwww","moves":"cb4 fg5 ed4 dc5"},
{"id":"IX-8","side":"w","board":"bbbbbb.bbbbb...bww..w..wwwwwwwww","moves":"cb4 fg5 ed4 ef6"},
{"id":"IX-9","side":"w","board":"bbbbbbbbbb.b....wwb.w..wwwwwwwww","moves":"cb4 fg5 ed4 gf4"},
{"id":"IX-10","side":"w","board":"bbbbbbbbbb.b....ww.bw..wwwwwwwww","moves":"cb4 fg5 ed4 gh4"},
{"id":"IX-11","side":"w","board":"bbbbbbbbbbb....bw...w.wwwwwwwwww","moves":"cb4 hg5"},
{"id":"IX-12","side":"b","board":"bbbbbbbbbbb.w....w.bw..wwwwwwwww","moves":"cb4 hg5 ba5 gh4 ed4"},
{"id":"IX-13","side":"w","board":"bbbbbbbb.bb.b..ww..bw.w.wwwwwwww","moves":"cb4 hg5 gf4 gh4 fg5 ba5"},
{"id":"IX-14","side":"w","board":"bbbbbbbb.bb.b..bw..ww.w.wwwwwwww","moves":"cb4 hg5 gh4 ba5"},
{"id":"IX-15","side":"w","board":"bbbbbbbbb.b...bbw..ww.w.wwwwwwww","moves":"cb4 hg5 gh4 de5"},
{"id":"IX-16","side":"b","board":"bbbbbbb.bbbb.w.b...ww.w.wwwwwwww","moves":"cb4 hg5 gh4 gh6 bc5"},
{"id":"IX-17","side":"b","board":"bbbbbbb.bbbb...bw..ww.wwwww.wwww","moves":"cb4 hg5 gh4 gh6 hg3"},
{"id":"IX-18","side":"b","board":"bbbbbbbbbbbb.....w..w.wwwwwwwwww","moves":"cd4"},
{"id":"IX-19","side":"b","board":"bbbbbbbb.bbbb....w..wwww.wwwwwww","moves":"cd4 ba5 bc3"},
{"id":"IX-20","side":"w","board":"bbbb.bbbbbbbb....w..wwww.wwwwwww","moves":"cd4 ba5 bc3 ab6"},
{"id":"IX-21","side":"w","board":"bbbb.bbbb.bbbb...w..wwwwwwww.www","moves":"cd4 ba5 bc3 ab6 ab2 dc5"},
{"id":"IX-22","side":"b","board":"bbbb.bbbbbbbb....ww.ww.w.wwwwwww","moves":"cd4 ba5 bc3 ab6 ef4"},
{"id":"IX-23","side":"b","board":"bbbb.bbbbbbbb....ww.www..wwwwwww","moves":"cd4 ba5 bc3 ab6 gf4"},
{"id":"IX-24","side":"w","board":"bbbbbbbb..bbb.b..w..wwww.wwwwwww","moves":"cd4 ba5 bc3 de5"},
{"id":"IX-25","side":"b","board":"bbbbbbbb..bbb.b..ww.ww.w.wwwwwww","moves":"cd4 ba5 bc3 de5 ef4"},
{"id":"IX-26","side":"b","board":"bbbbbbbb..bbb.b..ww.www..wwwwwww","moves":"cd4 ba5 bc3 de5 gf4"},
{"id":"X-1","side":"w","board":"bbbbbbbb.bbb.b...w..wwww.wwwwwww","moves":"b2-d4 b6-c5"},
{"id":"X-2","side":"w","board":"bbbbbbbbbb.b.b...w..wwww.wwwwwww","moves":"b2-d4 f6-c5"},
{"id":"X-3","side":"w","board":"bbbbbbbbbb.b..b..w..wwww.wwwwwww","moves":"b2-d4 f6-e5"},
{"id":"X-4","side":"w","board":"bbb.bbbbbbbb.....w.bwwww.wwwwwww","moves":"b2-d4 h8-h4"},
{"id":"X-5","side":"w","board":"bbbbbbb.bbbbb.w.....wwww.wwwwwww","moves":"b2-e5 g7-a5"},
{"id":"X-6","side":"w","board":"bbbbbbb.bbbb..w....bwwww.wwwwwww","moves":"b2-e5 g7-h4"},
{"id":"X-7","side":"w","board":"bbbbbbbbb.bb.b....w.wwww.wwwwwww","moves":"b2-f4 d6-c5"},
{"id":"X-8","side":"w","board":"bbbb.bbbbbbbb..w....wwww.wwwwwww","moves":"b2-g5 a7-a5"},
{"id":"X-9","side":"w","board":"bbbbb.bbbbbbb..w....wwww.wwwwwww","moves":"b2-g5 c7-a5"},
{"id":"X-10","side":"w","board":"bbbbbbbbb.bb..bw....wwww.wwwwwww","moves":"b2-g5 d6-e5"},
{"id":"X-11","side":"w","board":"bbbbbbb.bbbbb..w....wwww.wwwwwww","moves":"b2-g5 g7-a5"},
{"id":"X-12","side":"w","board":"bbbbbbbbbbb...bw....wwww.wwwwwww","moves":"b2-g5 h6-e5"},
{"id":"X-13","side":"w","board":"bbb.bbbbbbbbb..w....wwww.wwwwwww","moves":"b2-g5 h8-a5"},
{"id":"X-14","side":"w","board":"bbbb.bbbbbbbb......wwwww.wwwwwww","moves":"b2-h4 a7-a5"},
{"id":"X-15","side":"w","board":"bbbbbbbb.bbbb......wwwww.wwwwwww","moves":"b2-h4 b6-a5"},
{"id":"X-16","side":"w","board":"bbbbbbb.bbbb..b....wwwww.wwwwwww","moves":"b2-h4 g7-e5"},
{"id":"X-17","side":"w","board":"bbbbbbbbbbbwb.......wwww.wwwwwww","moves":"b2-h6 h6-a5"},
{"id":"X-18","side":"w","board":"bbbbbbbbbbbw..b.....wwww.wwwwwww","moves":"b2-h6 h6-e5"},
{"id":"X-19","side":"w","board":"bbbbbbbbbbbw......b.wwww.wwwwwww","moves":"b2-h6 h6-f4"},
{"id":"X-20","side":"w","board":"bbbbbbbb.bbb.......bwwwwwwwwwwww","moves":"--- b6-h4"},
{"id":"X-21","side":"w","board":"bbbb.bbbbbbbwb......wwwwwwwww.ww","moves":"c1-a5 a7-c5"},
{"id":"X-22","side":"w","board":"bbbb.bbbbbbbw.b.....wwwwwwwww.ww","moves":"c1-a5 a7-e5"},
{"id":"X-23","side":"w","board":"bb.bbbbbbbbbw......bwwwwwwwww.ww","moves":"c1-a5 f8-h4"},
{"id":"X-24","side":"w","board":"bbbbbbbb.bbb.wb.....wwwwwwwww.ww","moves":"c1-c5 b6-e5"},
{"id":"X-25","side":"w","board":"bbbbbbbb.bbb.b...w..wwwwwwwww.ww","moves":"c1-d4 b6-c5"},
{"id":"X-26","side":"w","board":"bbbbbbbbbbb....b.w..wwwwwwwww.ww","moves":"c1-d4 h6-g5"},
{"id":"XI-1","side":"w","board":"bbbbbbbb.b.bb.b..w..wwww.wwwwwww","moves":"cd4 ba5 bc3 fe5"},
{"id":"XI-2","side":"b","board":"bbbbbbbb.bb.b..b.w..wwwwwwww.www","moves":"cd4 ba5 bc3 hg5 ab2"},
{"id":"XI-3","side":"w","board":"bbbbbbbb.bb.b....wb.wwwwwwwww.ww","moves":"cd4 ba5 bc3 hg5 cb2 gf4"},
{"id":"XI-4","side":"b","board":"bbbbbbbb..bbb.b..ww.www.w.wwwwww","moves":"cd4 ba5 dc3 de5 gf4"},
{"id":"XI-5","side":"b","board":"bbbbbbbb..bbb.b..w.wwww.w.wwwwww","moves":"cd4 ba5 dc3 de5 gh4"},
{"id":"XI-6","side":"w","board":"bbbb.bbbbb.bb..b.w.wwww.w.wwwwww","moves":"cd4 ba5 dc3 fg5 gh4 ab6"},
{"id":"XI-7","side":"w","board":"bbbbbbbb..bbb.....b.w.wwwwwwwwww","moves":"cd4 ba5 de5 df4"},
{"id":"XI-8","side":"w","board":"bbbbbbbb..bbbb...ww.w..wwwwwwwww","moves":"cd4 ba5 ef4 dc5"},
{"id":"XI-9","side":"w","board":"bbbbbbbb..bbb.b..ww.w..wwwwwwwww","moves":"cd4 ba5 ef4 de5"},
{"id":"XI-10","side":"w","board":"bbbbb.bbb.bbbb...ww.w.www.wwwwww","moves":"cd4 ba5 ef4 cb6 de3 dc5"},
{"id":"XI-11","side":"w","board":"bbbbb.bbbbbb....bww.w.wwww.wwwww","moves":"cd4 ba5 ef4 cb6 fe3 ab4"},
{"id":"XI-12","side":"w","board":"bbbbbbbb.b.b...bbww.w.wwww.wwwww","moves":"cd4 ba5 ef4 fg5 fe3 ab4"},
{"id":"XI-13","side":"w","board":"bbbbbbbb..bbb.b..ww.w.w.wwwwwwww","moves":"cd4 ba5 gf4 de5"},
{"id":"XI-14","side":"w","board":"bbbbbb.b.b.bb..b..w.w.w.wwwwwwww","moves":"cd4 ba5 gf4 fe5 df6 eg5"},
{"id":"XI-15","side":"b","board":"bbbb.bbbbbbbbw.....ww.w.wwwwwwww","moves":"cd4 ba5 gh4 ab6 dc5"},
{"id":"XI-16","side":"w","board":"bbbbbbbb.bbb.b...w..w.wwwwwwwwww","moves":"cd4 bc5"},
{"id":"XI-17","side":"w","board":"bbbb.bbb..bb.bb.....wwww.wwwwwww","moves":"cd4 bc5 db6 ac5 bc3 de5"},
{"id":"XI-18","side":"w","board":"bbbb.bbb.b.b.bb.....wwww.wwwwwww","moves":"cd4 bc5 db6 ac5 bc3 fe5"},
{"id":"XI-19","side":"w","board":"bbbbb.bb.bbbb.......w.wwwwwwwwww","moves":"cd4 bc5 db6 ca5"},
{"id":"XI-20","side":"b","board":"bbbbb.bb.bbbb....w..w..wwwwwwwww","moves":"cd4 bc5 db6 ca5 ed4"},
{"id":"XI-21","side":"w","board":"bbbbb.bbbbbb.b...w..wwww.wwwwwww","moves":"cd4 dc5 bc3 cd6"},
{"id":"XI-22","side":"w","board":"bbbbb.bbb.bb.bb..w..wwwwwwww.www","moves":"cd4 dc5 bc3 cd6 ab2 de5"},
{"id":"XI-23","side":"b","board":"bbbbbb.bbbbb.b...w.wwww..wwwwwww","moves":"cd4 dc5 bc3 ed6 gh4"},
{"id":"XI-24","side":"w","board":"bbbbbbbb...bbb.bww..w.ww.wwwwwww","moves":"cd4 dc5 bc3 fg5 cb4 ba5"},
{"id":"XI-25","side":"w","board":"bbbbbb.bbb.b.b.bww..w.www.wwwwww","moves":"cd4 dc5 dc3 ed6 cb4 fg5"},
{"id":"XI-26","side":"w","board":"bbbbbbbbb..b.bb..w..wwwww.wwwwww","moves":"cd4 dc5 dc3 fe5"},
{"id":"XII-1","side":"w","board":"bbbbbbbbb.bb..b...w.wwwwwwwww.ww","moves":"c1-f4 d6-e5"},
{"id":"XII-2","side":"w","board":".bbbbbbbbbbb......wbwwwwwwwww.ww","moves":"c1-f4 b8-h4"},
{"id":"XII-3","side":"w","board":"bbbbbbbbbb.b...b...wwwwwwwwww.ww","moves":"c1-h4 f6-g5"},
{"id":"XII-4","side":"w","board":"bbbb.bbbbbbbw..b....w.wwwwwwwwww","moves":"c3-a5 a7-g5"},
{"id":"XII-5","side":"w","board":"bbbbbbbbb.bbw..b....w.wwwwwwwwww","moves":"c3-a5 d6-g5"},
{"id":"XII-6","side":"w","board":"bbbbbbbbb.bbw......bw.wwwwwwwwww","moves":"c3-a5 d6-h4"},
{"id":"XII-7","side":"w","board":"bbbbbbbbbb.bw.b.....w.wwwwwwwwww","moves":"c3-a5 f6-e5"},
{"id":"XII-8","side":"w","board":"bbb.bbbbbbbbw..b....w.wwwwwwwwww","moves":"c3-a5 h8-g5"},
{"id":"XII-9","side":"w","board":"bbbbbbbbbbb.w.b.....w.wwwwwwwwww","moves":"c3-a5 h6-e5"},
{"id":"XII-10","side":"w","board":"bbbb.bbbbbbbb...w...w.wwwwwwwwww","moves":"c3-b4 a7-a5"},
{"id":"XII-11","side":"w","board":"bbbb.bbbbbbb..b.w...w.wwwwwwwwww","moves":"c3-b4 a7-e5"},
{"id":"XII-12","side":"w","board":"bbbb.bbbbbbb....w..bw.wwwwwwwwww","moves":"c3-b4 a7-h4"},
{"id":"XII-13","side":"w","board":"bbb.bbbbbbbb...bw...w.wwwwwwwwww","moves":"c3-b4 h8-g5"},
{"id":"XII-14","side":"w","board":"bbbbbbbbbbb...b.w...w.wwwwwwwwww","moves":"c3-b4 h6-e5"},
{"id":"XII-15","side":"w","board":"bbbbbbbbbb.b.w.b....w.wwwwwwwwww","moves":"c3-c5 f6-g5"},
{"id":"XII-16","side":"w","board":"bbbbbbb.bbbb.wb.....w.wwwwwwwwww","moves":"c3-c5 g7-e5"},
{"id":"XII-17","side":"w","board":"bbbbbbb.bbbb.w.....bw.wwwwwwwwww","moves":"c3-c5 g7-h4"},
{"id":"XII-18","side":"w","board":"bbbb.bbbbbbb..b..w..w.wwwwwwwwww","moves":"c3-d4 a7-e5"},
{"id":"XII-19","side":"w","board":"bbbbbbbbb.bbb....w..w.wwwwwwwwww","moves":"c3-d4 d6-a5"},
{"id":"XII-20","side":"w","board":"bbbbbb.bbbbb..b..w..w.wwwwwwwwww","moves":"c3-d4 e7-e5"},
{"id":"XII-21","side":"w","board":"bbbbbbbbbb.b.b...w..w.wwwwwwwwww","moves":"c3-d4 f6-c5"},
{"id":"XII-22","side":"w","board":"bbb.bbbbbbbb...b.w..w.wwwwwwwwww","moves":"c3-d4 h8-g5"},
{"id":"XII-23","side":"w","board":"bbbbbbbbbbb...b..w..w.wwwwwwwwww","moves":"c3-d4 h6-e5"},
{"id":"XII-24","side":"w","board":"bbbbbbbb.bbbb.w.....w.wwwwwwwwww","moves":"c3-e5 b6-a5"},
{"id":"XII-25","side":"w","board":"bbbbbbb.bbbbb.w.....w.wwwwwwwwww","moves":"c3-e5 g7-a5"},
{"id":"XII-26","side":"w","board":"bbbbbbb.bbbb..wb....w.wwwwwwwwww","moves":"c3-e5 g7-g5"},
{"id":"XIII-1","side":"w","board":"bbbbbbbbb.b..b.b.w..wwwww.wwwwww","moves":"cd4 dc5 dc3 hg5"},
{"id":"XIII-2","side":"b","board":"bbbbb.bbbbbb.bw...w.w.w.wwwwwwww","moves":"cd4 dc5 gf4 cd6 de5"},
{"id":"XIII-3","side":"w","board":"bbbbbbbbb..b.bb..w.ww.w.wwwwwwww","moves":"cd4 dc5 gh4 fe5"},
{"id":"XIII-4","side":"w","board":"bbbbbbbbb.bb..b..w..w.wwwwwwwwww","moves":"cd4 de5"},
{"id":"XIII-5","side":"w","board":"bb.bbbbbbbbb..b..w..wwwwwwwww.ww","moves":"cd4 de5 bc3 ed6 cb2 fe7"},
{"id":"XIII-6","side":"w","board":"bb.bbbbbbbbb..b..ww.ww.w.wwwwwww","moves":"cd4 de5 bc3 ed6 ef4 fe7"},
{"id":"XIII-7","side":"b","board":"bbbbbb.bbbbb..b..ww.www..wwwwwww","moves":"cd4 de5 bc3 ed6 gf4"},
{"id":"XIII-8","side":"w","board":"bbbbbbbbb..b.....w.bww.w.wwwwwww","moves":"cd4 de5 bc3 ef4 eg5 fh4"},
{"id":"XIII-9","side":"b","board":"bbbbbbbbb.bb..b..w..wwwww.wwwwww","moves":"cd4 de5 dc3"},
{"id":"XIII-10","side":"w","board":"bbbbbbbbb.bb......w.wbw.wwwwwwww","moves":"cd4 de5 gf4 ec3"},
{"id":"XIII-11","side":"w","board":"bbbbbbbbb.bb.....w..w.wbwwwwwwww","moves":"cd4 de5 gf4 eg3"},
{"id":"XIII-12","side":"w","board":"bbbbbbbbb..b..b..w.ww.w..wwwwwww","moves":"cd4 de5 gh4 ec3 bd4 fe5"},
{"id":"XIII-13","side":"w","board":"bbbbbbbbbb.b..b..w..w.wwwwwwwwww","moves":"cd4 fe5"},
{"id":"XIII-14","side":"b","board":"bbbbbbb.bb.b..b.....wwww.wwwwwww","moves":"cd4 fe5 df6 ge5 bc3"},
{"id":"XIII-15","side":"b","board":"bbbbbbb.bb.b..b..w..w..wwwwwwwww","moves":"cd4 fe5 df6 ge5 ed4"},
{"id":"XIII-16","side":"b","board":"bbbbbbb.bb.b..b....ww.w.wwwwwwww","moves":"cd4 fe5 df6 ge5 gh4"},
{"id":"XIII-17","side":"w","board":"b.bbbbbbbb.b...b..w.w.w.wwwwwwww","moves":"cd4 fe5 df6 eg5 gf4 de7"},
{"id":"XIII-18","side":"w","board":"bbbbbb.bbbbb...b.w..wwww.wwwwwww","moves":"cd4 fg5 bc3 ef6"},
{"id":"XIII-19","side":"b","board":"bbbbbb.bbbbb...b.w..wwwwwwww.www","moves":"cd4 fg5 bc3 ef6 ab2"},
{"id":"XIII-20","side":"w","board":"bbbbbbb.b.bb..bb.w..wwwwwwww.www","moves":"cd4 fg5 bc3 gf6 ab2 de5"},
{"id":"XIII-21","side":"w","board":"bbbbbbb.bbbb.....w.bwwwwwwww.www","moves":"cd4 fg5 bc3 gf6 ab2 gh4"},
{"id":"XIII-22","side":"w","board":"bbbbbbbbbb.b.....wb.wwww.wwwwwww","moves":"cd4 fg5 bc3 gf4"},
{"id":"XIII-23","side":"w","board":"bbbbbbbbb..b..b.ww.bw.ww.wwwwwww","moves":"cd4 fg5 bc3 gh4 cb4 de5"},
{"id":"XIII-24","side":"w","board":"bbbbbbbbbb.....bww.bw.ww.wwwwwww","moves":"cd4 fg5 bc3 gh4 cb4 hg5"},
{"id":"XIII-25","side":"b","board":"bbbbbbbbbb.b.w.b....w.wwwwwwwwww","moves":"cd4 fg5 dc5"},
{"id":"XIII-26","side":"w","board":"bbbbbb.b.bbb.b.b.w..wwwwwwwwww.w","moves":"cd4 fg5 dc3 ef6 ed2 bc5"},
{"id":"XIV-1","side":"w","board":"bbbbbbb.bbbb..w....bw.wwwwwwwwww","moves":"c3-e5 g7-h4"},
{"id":"XIV-2","side":"w","board":"bbbbbbbbbbbb......w.w.wwwwwwwwww","moves":"c3-f4 ---"},
{"id":"XIV-3","side":"w","board":"bbbb.bbbbbbb..b...w.w.wwwwwwwwww","moves":"c3-f4 a7-e5"},
{"id":"XIV-4","side":"w","board":"bbbbbbbbbb.b....b.w.w.wwwwwwwwww","moves":"c3-f4 f6-b4"},
{"id":"XIV-5","side":"w","board":"bbbbbbbbbb.b..b...w.w.wwwwwwwwww","moves":"c3-f4 f6-e5"},
{"id":"XIV-6","side":"w","board":"bbb.bbbbbbbb......wbw.wwwwwwwwww","moves":"c3-f4 h8-h4"},
{"id":"XIV-7","side":"w","board":"bbbbbbbbbbb..b....w.w.wwwwwwwwww","moves":"c3-f4 h6-c5"},
{"id":"XIV-8","side":"w","board":"bbbb.bbbbbbbb..w....w.wwwwwwwwww","moves":"c3-g5 a7-a5"},
{"id":"XIV-9","side":"w","board":"bbbb.bbbbbbb..bw....w.wwwwwwwwww","moves":"c3-g5 a7-e5"},
{"id":"XIV-10","side":"w","board":"bbbbbbbb.bbb.b.w....w.wwwwwwwwww","moves":"c3-g5 b6-c5"},
{"id":"XIV-11","side":"w","board":"bbbbb.bbbbbb.b.w....w.wwwwwwwwww","moves":"c3-g5 c7-c5"},
{"id":"XIV-12","side":"w","board":"bbbbb.bbbbbb..bw....w.wwwwwwwwww","moves":"c3-g5 c7-e5"},
{"id":"XIV-13","side":"w","board":"bbbbbbb.bbbb.b.w....w.wwwwwwwwww","moves":"c3-g5 g7-c5"},
{"id":"XIV-14","side":"w","board":"bbbbbbb.bbbb..bw....w.wwwwwwwwww","moves":"c3-g5 g7-e5"},
{"id":"XIV-15","side":"w","board":"bbb.bbbbbbbbb..w....w.wwwwwwwwww","moves":"c3-g5 h8-a5"},
{"id":"XIV-16","side":"w","board":"bbbbbbbbbbbb.......ww.wwwwwwwwww","moves":"c3-h4 ---"},
{"id":"XIV-17","side":"w","board":"bbbb.bbbbbbb...b...ww.wwwwwwwwww","moves":"c3-h4 a7-g5"},
{"id":"XIV-18","side":"w","board":"bbbbbbbbbb.bb......ww.wwwwwwwwww","moves":"c3-h4 f6-a5"},
{"id":"XIV-19","side":"w","board":"bbbbbbbbbb.b..b....ww.wwwwwwwwww","moves":"c3-h4 f6-e5"},
{"id":"XIV-20","side":"w","board":"bbbbbbb.bbbb.b.....ww.wwwwwwwwww","moves":"c3-h4 g7-c5"},
{"id":"XIV-21","side":"w","board":"bbbbbbbbbbb..b.....ww.wwwwwwwwww","moves":"c3-h4 h6-c5"},
{"id":"XIV-22","side":"w","board":"bbbbbbbbbbbwb.......w.wwwwwwwwww","moves":"c3-h6 h6-a5"},
{"id":"XIV-23","side":"w","board":"bbbbb.bbbbbbb.......wwwwwwwwwwww","moves":"--- c7-a5"},
{"id":"XIV-24","side":"w","board":"bbbbb.bbbbbb...b....wwwwwwwwwwww","moves":"--- c7-g5"},
{"id":"XIV-25","side":"w","board":"bbbbbbbbbbbbw.......wwwww.wwwwww","moves":"d2-a5 ---"},
{"id":"XIV-26","side":"w","board":"bbbbbbbb.bbbw......bwwwww.wwwwww","moves":"d2-a5 b6-h4"},
{"id":"XV-1","side":"w","board":"bbbbbbb.b.bb..bb.ww.www.w.wwwwww","moves":"cd4 fg5 dc3 gf6 gf4 de5"},
{"id":"XV-2","side":"b","board":"bbbbbbbbbb.b....ww.bw.www.wwwwww","moves":"cd4 fg5 dc3 gh4 cb4"},
{"id":"XV-3","side":"w","board":"bbb.bbbbbbbb...b.ww.www..wwwwwww","moves":"cd4 fg5 gf4 gf6 bc3 hg7"},
{"id":"XV-4","side":"w","board":"bbbbbbb.bbbb.....wwbwww..wwwwwww","moves":"cd4 fg5 gf4 gf6 bc3 gh4"},
{"id":"XV-5","side":"w","board":"bbbbbbbb.b.bb..b.w.ww.w.wwwwwwww","moves":"cd4 fg5 gh4 ba5"},
{"id":"XV-6","side":"w","board":"bbbbbbbbb..b.b.b.w.ww.w.wwwwwwww","moves":"cd4 fg5 gh4 dc5"},
{"id":"XV-7","side":"w","board":"bbbbbb.bb..b.b.b.w..w.w.wwwwwwww","moves":"cd4 fg5 gh4 dc5 hf6 eg5"},
{"id":"XV-8","side":"w","board":"bbbbbb.bbbbb...b.w.ww.w.wwwwwwww","moves":"cd4 fg5 gh4 ef6"},
{"id":"XV-9","side":"w","board":"bbbbbbbbbb.b.....wbww.w.wwwwwwww","moves":"cd4 fg5 gh4 gf4"},
{"id":"XV-10","side":"w","board":"bbbbbbbbbbb....b.w..w.wwwwwwwwww","moves":"cd4 hg5"},
{"id":"XV-11","side":"w","board":"bbbbbbbbbbb......wb.wwww.wwwwwww","moves":"cd4 hg5 bc3 gf4"},
{"id":"XV-12","side":"b","board":"bbbbbbbbbbb....w.w..ww.w.wwwwwww","moves":"cd4 hg5 bc3 gf4 eg5"},
{"id":"XV-13","side":"w","board":"bbbbbbbbbbb......w.bwwww.wwwwwww","moves":"cd4 hg5 bc3 gh4"},
{"id":"XV-14","side":"w","board":"bbbbbbbbb.b...b.ww.bw.ww.wwwwwww","moves":"cd4 hg5 bc3 gh4 cb4 de5"},
{"id":"XV-15","side":"b","board":"bbbbbbbbbbb...w..w.bw.w.wwwwwwww","moves":"cd4 hg5 gf4 gh4 fe5"},
{"id":"XV-16","side":"w","board":"bbbbbbbbb.b..b.w.w.bw.w.wwwwwwww","moves":"cd4 hg5 gf4 gh4 fg5 dc5"},
{"id":"XV-17","side":"w","board":"bbbbbbbbb.b...bw.w.bw.w.wwwwwwww","moves":"cd4 hg5 gf4 gh4 fg5 de5"},
{"id":"XV-18","side":"w","board":"bbbbbbbbbb....bw.w.bw.w.wwwwwwww","moves":"cd4 hg5 gf4 gh4 fg5 fe5"},
{"id":"XV-19","side":"b","board":"bbbbbbbbbbbb.....w..ww.wwwwwwwww","moves":"ed4"},
{"id":"XV-20","side":"w","board":"bbbbbbbb.bbbb....w..ww.wwwwwwwww","moves":"ed4 ba5"},
{"id":"XV-21","side":"w","board":"bbbbbbbb...bbw.b.....w.wwwwwwwww","moves":"ed4 ba5 dc5 db4 ac5 fg5"},
{"id":"XV-22","side":"w","board":"bbbb.bbbbbbbb....w..wwwwww.wwwww","moves":"ed4 ba5 fe3 ab6"},
{"id":"XV-23","side":"w","board":"bbbbb.bbbbbbb....w..wwwwww.wwwww","moves":"ed4 ba5 fe3 cb6"},
{"id":"XV-24","side":"w","board":"bbbb.bbbb.bbb.b..w.wwww.ww.wwwww","moves":"ed4 ba5 fe3 de5 gh4 ab6"},
{"id":"XV-25","side":"w","board":"bbbbb.bbb.bbb.b..w.wwww.ww.wwwww","moves":"ed4 ba5 fe3 de5 gh4 cb6"},
{"id":"XV-26","side":"w","board":"bbbbbbbb.b.bb.b..w..wwwwww.wwwww","moves":"ed4 ba5 fe3 fe5"},
{"id":"XVI-1","side":"w","board":"bbbbbb.bbbbbw..b....wwwww.wwwwww","moves":"d2-a5 e7-g5"},
{"id":"XVI-2","side":"w","board":"bbbbbbb.bbbbw.......wwwwwbwwwwww","moves":"d2-a5 g7-d2"},
{"id":"XVI-3","side":"w","board":"bbbbbbb.bbbbw.b.....wwwww.wwwwww","moves":"d2-a5 g7-e5"},
{"id":"XVI-4","side":"w","board":"bbbbbbbbbbbb....w...wwwww.wwwwww","moves":"d2-b4 ---"},
{"id":"XVI-5","side":"w","board":"bbbb.bbbbbbb...bw...wwwww.wwwwww","moves":"d2-b4 a7-g5"},
{"id":"XVI-6","side":"w","board":"bbbb.bbbbbbb....w..bwwwww.wwwwww","moves":"d2-b4 a7-h4"},
{"id":"XVI-7","side":"w","board":"bbbbbbbbb.bb..b.w...wwwww.wwwwww","moves":"d2-b4 d6-e5"},
{"id":"XVI-8","side":"w","board":"bbb.bbbbbbbbb...w...wwwww.wwwwww","moves":"d2-b4 h8-a5"},
{"id":"XVI-9","side":"w","board":"bbb.bbbbbbbb...bw...wwwww.wwwwww","moves":"d2-b4 h8-g5"},
{"id":"XVI-10","side":"w","board":"bbb.bbbbbbbb....w..bwwwww.wwwwww","moves":"d2-b4 h8-h4"},
{"id":"XVI-11","side":"w","board":"bbbbbbbbbbbb.w......wwwww.wwwwww","moves":"d2-c5 ---"},
{"id":"XVI-12","side":"w","board":"bbbb.bbbbbbb.w......wwwwwbwwwwww","moves":"d2-c5 a7-d2"},
{"id":"XVI-13","side":"w","board":"bbbbbbbb.bbb.w.b....wwwww.wwwwww","moves":"d2-c5 b6-g5"},
{"id":"XVI-14","side":"w","board":"bbbbbbbbb.bb.w.....bwwwww.wwwwww","moves":"d2-c5 d6-h4"},
{"id":"XVI-15","side":"w","board":"bbbbbbbbbbbb.....w..wwwww.wwwwww","moves":"d2-d4 ---"},
{"id":"XVI-16","side":"w","board":"bbbb.bbbbbbb...b.w..wwwww.wwwwww","moves":"d2-d4 a7-g5"},
{"id":"XVI-17","side":"w","board":"bbbb.bbbbbbb.....w.bwwwww.wwwwww","moves":"d2-d4 a7-h4"},
{"id":"XVI-18","side":"w","board":"bbbbbbbb.bbbb....w..wwwww.wwwwww","moves":"d2-d4 b6-a5"},
{"id":"XVI-19","side":"w","board":"bbbbbbbb.bbb...b.w..wwwww.wwwwww","moves":"d2-d4 b6-g5"},
{"id":"XVI-20","side":"w","board":"bbbbb.bbbbbb.....w.bwwwww.wwwwww","moves":"d2-d4 c7-h4"},
{"id":"XVI-21","side":"w","board":"bbbbbbbbb.bb.....w.bwwwww.wwwwww","moves":"d2-d4 d6-h4"},
{"id":"XVI-22","side":"w","board":"bbbbbbbbbb.b..b..w..wwwww.wwwwww","moves":"d2-d4 f6-e5"},
{"id":"XVI-23","side":"w","board":"bbbbbbbbbb.b...b.w..wwwww.wwwwww","moves":"d2-d4 f6-g5"},
{"id":"XVI-24","side":"w","board":"bbb.bbbbbbbb.....w.bwwwww.wwwwww","moves":"d2-d4 h8-h4"},
{"id":"XVI-25","side":"w","board":"bbbbbbbbbbb....b.w..wwwww.wwwwww","moves":"d2-d4 h6-g5"},
{"id":"XVI-26","side":"w","board":"bbbbbbb.bbbb..w....bwwwww.wwwwww","moves":"d2-e5 g7-h4"},
{"id":"XVII-1","side":"w","board":"bbbbbbbb.b.bb....w.bwwwwwwwwwww.","moves":"ed4 ba5 fe3 fg5 gf2 gh4"},
{"id":"XVII-2","side":"b","board":"bbbbbbbb.bb.b..b.w..wwwwwwwwwww.","moves":"ed4 ba5 fe3 hg5 gf2"},
{"id":"XVII-3","side":"w","board":"bbbbbbbb.b.bb..b.ww.ww..wwwwwwww","moves":"ed4 ba5 gf4 fg5"},
{"id":"XVII-4","side":"w","board":"bbbbbbbb.bbb.b...w..ww.wwwwwwwww","moves":"ed4 bc5"},
{"id":"XVII-5","side":"w","board":"bbbb.bbb.bb..b.b....wwwww.wwwwww","moves":"ed4 bc5 db6 ac5 de3 hg5"},
{"id":"XVII-6","side":"w","board":"bbbb.bbb.b.b.bb...w.ww..wwwwwwww","moves":"ed4 bc5 db6 ac5 gf4 fe5"},
{"id":"XVII-7","side":"w","board":"bbbb.bbb..bb.bb....www..wwwwwwww","moves":"ed4 bc5 db6 ac5 gh4 de5"},
{"id":"XVII-8","side":"w","board":"bbbbb.bb.bbbb.......ww.wwwwwwwww","moves":"ed4 bc5 db6 ca5"},
{"id":"XVII-9","side":"w","board":"bbbb..bbbbbbb...w....w.wwwwwwwww","moves":"ed4 bc5 db6 ca5 ab4 ab6"},
{"id":"XVII-10","side":"w","board":"bbbbb.bb.bb.b..bw....w.wwwwwwwww","moves":"ed4 bc5 db6 ca5 ab4 hg5"},
{"id":"XVII-11","side":"w","board":"bbbbbbbbb..b...bww..w..www.wwwww","moves":"ed4 dc5 cb4 ce3 fd4 fg5"},
{"id":"XVII-12","side":"w","board":"bbbbb.bbbbbb....w.w.w..ww.wwwwww","moves":"ed4 dc5 cb4 ce3 df4 cd6"},
{"id":"XVII-13","side":"w","board":"bbbbb.bbbbbb.b...w..wwwwww.wwwww","moves":"ed4 dc5 fe3 cd6"},
{"id":"XVII-14","side":"w","board":"bbbbbb.bbbbb.b...w..wwwwww.wwwww","moves":"ed4 dc5 fe3 ed6"},
{"id":"XVII-15","side":"w","board":"bbbbb.bbbb.b.b.b.w.wwww.ww.wwwww","moves":"ed4 dc5 fe3 fg5 gh4 cd6"},
{"id":"XVII-16","side":"w","board":"bbbbbbb.b.bb.b.b.w.wwww.ww.wwwww","moves":"ed4 dc5 fe3 fg5 gh4 gf6"},
{"id":"XVII-17","side":"w","board":"bbbbbbbbb..b.b...wbwwww.ww.wwwww","moves":"ed4 dc5 fe3 fg5 gh4 gf4"},
{"id":"XVII-18","side":"b","board":"bbbbbbbbb.b..b.b.ww.ww.www.wwwww","moves":"ed4 dc5 fe3 hg5 ef4"},
{"id":"XVII-19","side":"w","board":"bbbbbbbb..bbb....w.www..ww.wwwww","moves":"ed4 dc5 gh4 ce3 fd4 ba5"},
{"id":"XVII-20","side":"w","board":"bbbbbbbbb.bb..b..w..ww.wwwwwwwww","moves":"ed4 de5"},
{"id":"XVII-21","side":"w","board":"bbbbb.bbbbbb..b.ww...w.wwwwwwwww","moves":"ed4 de5 ab4 cd6"},
{"id":"XVII-22","side":"w","board":"bbbbbb.bbbbb..b.ww...w.wwwwwwwww","moves":"ed4 de5 ab4 ed6"},
{"id":"XVII-23","side":"w","board":"bbbbbb.bbbbb..b..w..wwwww.wwwwww","moves":"ed4 de5 de3 ed6"},
{"id":"XVII-24","side":"b","board":"bbbbbbbbb.bb..b..w..wwwwww.wwwww","moves":"ed4 de5 fe3"},
{"id":"XVII-25","side":"w","board":"bbbbbbbbb.b....b.w.www..ww.wwwww","moves":"ed4 de5 gf4 eg3 fh4 hg5"},
{"id":"XVII-26","side":"b","board":"bbbbbbbbb.b...bb.w.wwww.ww.wwwww","moves":"ed4 de5 gh4 hg5 fe3"},
{"id":"XVIII-1","side":"w","board":"bbbbbbbbbbbb......w.wwwww.wwwwww","moves":"d2-f4 ---"},
{"id":"XVIII-2","side":"w","board":"bbbbbbbb.bbb.b....w.wwwww.wwwwww","moves":"d2-f4 b6-c5"},
{"id":"XVIII-3","side":"w","board":"bbbbbbbbb.bbb.....w.wwwww.wwwwww","moves":"d2-f4 d6-a5"},
{"id":"XVIII-4","side":"w","board":"bbbbbb.bbbbbb.....w.wwwww.wwwwww","moves":"d2-f4 e7-a5"},
{"id":"XVIII-5","side":"w","board":"bbbbbbbbbbb....w...bwwwww.wwwwww","moves":"d2-g5 h6-h4"},
{"id":"XVIII-6","side":"w","board":"bbbbbbbb.bbb.b.....wwwwww.wwwwww","moves":"d2-h4 b6-c5"},
{"id":"XVIII-7","side":"w","board":"bbbbbb.bbbbb.b.....wwwwww.wwwwww","moves":"d2-h4 e7-c5"},
{"id":"XVIII-8","side":"w","board":"bbbbbbbbbb.b...b...wwwwww.wwwwww","moves":"d2-h4 f6-g5"},
{"id":"XVIII-9","side":"w","board":"bbbbbbb.bbbb..b....wwwwww.wwwwww","moves":"d2-h4 g7-e5"},
{"id":"XVIII-10","side":"w","board":"bbbbbbbbbbb...b....wwwwww.wwwwww","moves":"d2-h4 h6-e5"},
{"id":"XVIII-11","side":"w","board":"bbbbbbbbb.bbb.......wwwwwwwwwwww","moves":"--- d6-a5"},
{"id":"XVIII-12","side":"w","board":"bbbbbbbbb.bb...b....wwwwwwwwwwww","moves":"--- d6-g5"},
{"id":"XVIII-13","side":"w","board":"bbbbbbbbb.bb.......bwwwwwwwwwwww","moves":"--- d6-h4"},
{"id":"XVIII-14","side":"w","board":"bb.bbbbbbbbbwb......wwwwwwwwww.w","moves":"e1-a5 f8-c5"},
{"id":"XVIII-15","side":"w","board":"bbbbbbbbb.bb.b..w...wwwwwwwwww.w","moves":"e1-b4 d6-c5"},
{"id":"XVIII-16","side":"w","board":"bbbbbbbb.bbb.b...w..wwwwwwwwww.w","moves":"e1-d4 b6-c5"},
{"id":"XVIII-17","side":"w","board":"bbbbb.bbbbbb..b..w..wwwwwwwwww.w","moves":"e1-d4 c7-e5"},
{"id":"XVIII-18","side":"w","board":"bbbbbb.bbbbb..b..w..wwwwwwwwww.w","moves":"e1-d4 e7-e5"},
{"id":"XVIII-19","side":"w","board":"bbbbbbbbbbbbw.......ww.wwwwwwwww","moves":"e3-a5 ---"},
{"id":"XVIII-20","side":"w","board":"bbbb.bbbbbbbw.b.....ww.wwwwwwwww","moves":"e3-a5 a7-e5"},
{"id":"XVIII-21","side":"w","board":"bbbb.bbbbbbbw..b....ww.wwwwwwwww","moves":"e3-a5 a7-g5"},
{"id":"XVIII-22","side":"w","board":"bbbbbbbb.bbbwb......ww.wwwwwwwww","moves":"e3-a5 b6-c5"},
{"id":"XVIII-23","side":"w","board":"bbbbbbbbb.bbw.b.....ww.wwwwwwwww","moves":"e3-a5 d6-e5"},
{"id":"XVIII-24","side":"w","board":"bbbbbb.bbbbbw..b....ww.wwwwwwwww","moves":"e3-a5 e7-g5"},
{"id":"XVIII-25","side":"w","board":"bbbbbbbbbb.bw...b...ww.wwwwwwwww","moves":"e3-a5 f6-b4"},
{"id":"XVIII-26","side":"w","board":"bbbbbbb.bbbbw...b...ww.wwwwwwwww","moves":"e3-a5 g7-b4"},
{"id":"XIX-1","side":"w","board":"bbbbbbbbbb.b..b..w..ww.wwwwwwwww","moves":"ed4 fe5"},
{"id":"XIX-2","side":"w","board":"bbb.bbbbbb.b..b.w....w.wwwwwwwww","moves":"ed4 fe5 df6 ge5 ab4 hg7"},
{"id":"XIX-3","side":"w","board":"bbbbbbb.bb....bbw....w.wwwwwwwww","moves":"ed4 fe5 df6 ge5 ab4 hg5"},
{"id":"XIX-4","side":"w","board":"bbb.bbbbbb.b..b....www..wwwwwwww","moves":"ed4 fe5 df6 ge5 gh4 hg7"},
{"id":"XIX-5","side":"b","board":"bbbbbb.bbb.b...b....wwwwww.wwwww","moves":"ed4 fe5 df6 eg5 fe3"},
{"id":"XIX-6","side":"w","board":"bbbbbbbbbb.b...b.w..ww.wwwwwwwww","moves":"ed4 fg5"},
{"id":"XIX-7","side":"w","board":"bbbbbbbb.b.b.b.b.w..wwwwww.wwwww","moves":"ed4 fg5 fe3 bc5"},
{"id":"XIX-8","side":"w","board":"bbbbbb.bbbbb...b.w..wwwwww.wwwww","moves":"ed4 fg5 fe3 ef6"},
{"id":"XIX-9","side":"w","board":"bbbbbb.b.bbb.b.b.w..wwwwwwwwwww.","moves":"ed4 fg5 fe3 ef6 gf2 bc5"},
{"id":"XIX-10","side":"w","board":"bbbbbbb.bbbb...b.w..wwwwww.wwwww","moves":"ed4 fg5 fe3 gf6"},
{"id":"XIX-11","side":"w","board":"bbbbbbbb.b.bb..b.w.www..wwwwwwww","moves":"ed4 fg5 gh4 ba5"},
{"id":"XIX-12","side":"w","board":"bbbbbbbbb..b.b.b.w.www..wwwwwwww","moves":"ed4 fg5 gh4 dc5"},
{"id":"XIX-13","side":"w","board":"bbbbbb.bbbbb...b.w.www..wwwwwwww","moves":"ed4 fg5 gh4 ef6"},
{"id":"XIX-14","side":"w","board":"bbbbbbb.bbbb...b.w.www..wwwwwwww","moves":"ed4 fg5 gh4 gf6"},
{"id":"XIX-15","side":"w","board":"bbbbbbbbbbb....b.w..ww.wwwwwwwww","moves":"ed4 hg5"},
{"id":"XIX-16","side":"w","board":"bbbbbbbbb.b...bbww..w..wwwwwwwww","moves":"ed4 hg5 cb4 de5"},
{"id":"XIX-17","side":"w","board":"bbbbbbbbbbb.....wwb.w..wwwwwwwww","moves":"ed4 hg5 cb4 gf4"},
{"id":"XIX-18","side":"w","board":"bbbbbbbbbbb.....ww.bw..wwwwwwwww","moves":"ed4 hg5 cb4 gh4"},
{"id":"XIX-19","side":"w","board":"bbbbbbbbbbb......wb.wwwwww.wwwww","moves":"ed4 hg5 fe3 gf4"},
{"id":"XIX-20","side":"w","board":"bbbbbbb.bbbb...b.w.www..wwwwwwww","moves":"ed4 hg5 gh4 gh6"},
{"id":"XIX-21","side":"b","board":"bbbbbbbbbbbb......w.ww.wwwwwwwww","moves":"ef4"},
{"id":"XIX-22","side":"w","board":"bbbb.bbbb.bbbb...ww.w.www.wwwwww","moves":"ef4 ba5 de3 ab6 cd4 dc5"},
{"id":"XIX-23","side":"w","board":"bbbbb.bbbb.bb.b...w.wwwwwwwww.ww","moves":"ef4 ba5 de3 cb6 cd2 fe5"},
{"id":"XIX-24","side":"b","board":"bbbbbbbb.bbbb.....w.wwwwww.wwwww","moves":"ef4 ba5 fe3"},
{"id":"XIX-25","side":"w","board":"bbbb.bbbbb.bb..b..w.wwwwwwwwwww.","moves":"ef4 ba5 fe3 ab6 gf2 fg5"},
{"id":"XIX-26","side":"b","board":"bbbbbbbb.b.bb.b..ww.w.wwww.wwwww","moves":"ef4 ba5 fe3 fe5 cd4"},
{"id":"XX-1","side":"w","board":"bbb.bbbbbbbbw.b.....ww.wwwwwwwww","moves":"e3-a5 h8-e5"},
{"id":"XX-2","side":"w","board":"bbb.bbbbbbbbw......bww.wwwwwwwww","moves":"e3-a5 h8-h4"},
{"id":"XX-3","side":"w","board":"bbbbbbbbbbbb....w...ww.wwwwwwwww","moves":"e3-b4 ---"},
{"id":"XX-4","side":"w","board":"bbbb.bbbbbbb.b..w...ww.wwwwwwwww","moves":"e3-b4 a7-c5"},
{"id":"XX-5","side":"w","board":"bbbb.bbbbbbb..b.w...ww.wwwwwwwww","moves":"e3-b4 a7-e5"},
{"id":"XX-6","side":"w","board":"bbbb.bbbbbbb....w..bww.wwwwwwwww","moves":"e3-b4 a7-h4"},
{"id":"XX-7","side":"w","board":"bbbbbbbb.bbb....w.b.ww.wwwwwwwww","moves":"e3-b4 b6-f4"},
{"id":"XX-8","side":"w","board":"bbbbbbbb.bbb...bw...ww.wwwwwwwww","moves":"e3-b4 b6-g5"},
{"id":"XX-9","side":"w","board":"bbbbbbbbbb.b..b.w...ww.wwwwwwwww","moves":"e3-b4 f6-e5"},
{"id":"XX-10","side":"w","board":"bbb.bbbbbbbb..b.w...ww.wwwwwwwww","moves":"e3-b4 h8-e5"},
{"id":"XX-11","side":"w","board":"bbb.bbbbbbbb....w..bww.wwwwwwwww","moves":"e3-b4 h8-h4"},
{"id":"XX-12","side":"w","board":"bbbbbbbbwbbb....b...ww.wwwwwwwww","moves":"e3-b6 b6-b4"},
{"id":"XX-13","side":"w","board":"bbbbbbbbb.bb.w.b....ww.wwwwwwwww","moves":"e3-c5 d6-g5"},
{"id":"XX-14","side":"w","board":"bbbbbbb.bbbb.w.....bww.wwwwwwwww","moves":"e3-c5 g7-h4"},
{"id":"XX-15","side":"w","board":"bbbbbbbbbbbb.....w..ww.wwwwwwwww","moves":"e3-d4 ---"},
{"id":"XX-16","side":"w","board":"bbbb.bbbbbbb..b..w..ww.wwwwwwwww","moves":"e3-d4 a7-e5"},
{"id":"XX-17","side":"w","board":"bbbb.bbbbbbb...b.w..ww.wwwwwwwww","moves":"e3-d4 a7-g5"},
{"id":"XX-18","side":"w","board":"bbbbbbbbb.bbb....w..ww.wwwwwwwww","moves":"e3-d4 d6-a5"},
{"id":"XX-19","side":"w","board":"bbbbbbbbb.bb.....w.bww.wwwwwwwww","moves":"e3-d4 d6-h4"},
{"id":"XX-20","side":"w","board":"bb.bbbbbbbbb.b...w..ww.wwwwwwwww","moves":"e3-d4 f8-c5"},
{"id":"XX-21","side":"w","board":"bbbbbbbbbbbb......w.ww.wwwwwwwww","moves":"e3-f4 ---"},
{"id":"XX-22","side":"w","board":"bbbb.bbbbbbb..b...w.ww.wwwwwwwww","moves":"e3-f4 a7-e5"},
{"id":"XX-23","side":"w","board":".bbbbbbbbbbb...b..w.ww.wwwwwwwww","moves":"e3-f4 b8-g5"},
{"id":"XX-24","side":"w","board":"bbbbbbbbb.bbb.....w.ww.wwwwwwwww","moves":"e3-f4 d6-a5"},
{"id":"XX-25","side":"w","board":"bbbbbbbbbb.b.b....w.ww.wwwwwwwww","moves":"e3-f4 f6-c5"},
{"id":"XX-26","side":"w","board":"bbbbbbb.bbbbb.....w.ww.wwwwwwwww","moves":"e3-f4 g7-a5"},
{"id":"XXI-1","side":"b","board":"bbbbbbbb.bbbb.....wwww..wwwwwwww","moves":"ef4 ba5 gh4"},
{"id":"XXI-2","side":"b","board":"bbbbbbbb.b.b.b.bw.w.w.www.wwwwww","moves":"ef4 bc5 cb4 fg5 de3"},
{"id":"XXI-3","side":"w","board":"bbbb.bbbbb.b.b.b.ww.w.www.wwwwww","moves":"ef4 bc5 de3 ab6 cd4 fg5"},
{"id":"XXI-4","side":"w","board":"bbbbb.bbbb.b.bb..ww.w.wwww.wwwww","moves":"ef4 bc5 fe3 cb6 cd4 fe5"},
{"id":"XXI-5","side":"w","board":"bbbb.bbbbb.b.bb...wwww.wwww.wwww","moves":"ef4 bc5 gh4 ab6 hg3 fe5"},
{"id":"XXI-6","side":"w","board":"bbbbbb.bbbbb.b..w.w.w..wwwwwwwww","moves":"ef4 dc5 cb4 ed6"},
{"id":"XXI-7","side":"w","board":"bbbbbb.bb.bb.bb.w.www...wwwwwwww","moves":"ef4 dc5 cb4 ed6 gh4 de5"},
{"id":"XXI-8","side":"b","board":"bbbbbbbbb.bb.b....w.wwwww.wwwwww","moves":"ef4 dc5 de3"},
{"id":"XXI-9","side":"b","board":"bbbbbbbbb.bb.b....w.wwwwww.wwwww","moves":"ef4 dc5 fe3"},
{"id":"XXI-10","side":"w","board":"bbbbbb.bbb.b.bb...wwww.wwww.wwww","moves":"ef4 dc5 gh4 ed6 hg3 fe5"},
{"id":"XXI-11","side":"w","board":"bbbbbbbbb.bb..b...w.ww.wwwwwwwww","moves":"ef4 de5"},
{"id":"XXI-12","side":"b","board":"bbbbbb.bb.bb.b......wwwww.wwwwww","moves":"ef4 de5 fd6 ec5 de3"},
{"id":"XXI-13","side":"w","board":"bbbbb.bbb..b..bb....wwwww.wwwwww","moves":"ef4 de5 fd6 ce5 de3 fg5"},
{"id":"XXI-14","side":"b","board":"bbbbbbbbbb.b.....ww.w..w.wwwwwww","moves":"ef4 fe5 cd4 ec3 bd4"},
{"id":"XXI-15","side":"b","board":"bbbbbbbbbb.b..b...w.wwwww.wwwwww","moves":"ef4 fe5 de3"},
{"id":"XXI-16","side":"w","board":"bbbbb.bbbb.bb.b.w.w..wwww.wwwwww","moves":"ef4 fe5 de3 ba5 ab4 cb6"},
{"id":"XXI-17","side":"w","board":"bbbbbbbbbb.b...b..w.ww.wwwwwwwww","moves":"ef4 fg5"},
{"id":"XXI-18","side":"b","board":"bbbbbbbbbb.b....ww..w..www.wwwww","moves":"ef4 fg5 cb4 ge3 fd4"},
{"id":"XXI-19","side":"w","board":"bbbbbb.bbbbb....w.w.w..ww.wwwwww","moves":"ef4 fg5 cb4 ge3 df4 ef6"},
{"id":"XXI-20","side":"w","board":"bbbbbbbbb..b..w....bww..wwwwwwww","moves":"ef4 fg5 fe5 df4 ge5 gh4"},
{"id":"XXI-21","side":"w","board":"bbbbbbbbb..b..b...wbwwwwwwwwww.w","moves":"ef4 fg5 fe3 gh4 ef2 de5"},
{"id":"XXI-22","side":"w","board":"bbbbbbbb.b.bb.....wbwwwwwwwwwww.","moves":"ef4 fg5 fe3 gh4 gf2 ba5"},
{"id":"XXI-23","side":"w","board":"bbbbbbbbb..b..b...wbwwwwwwwwwww.","moves":"ef4 fg5 fe3 gh4 gf2 de5"},
{"id":"XXI-24","side":"b","board":"bbbbbbbbbbbb......w.www.wwwwwwww","moves":"gf4"},
{"id":"XXI-25","side":"w","board":"bbbbbbbb.bbbb.....w.www.wwwwwwww","moves":"gf4 ba5"},
{"id":"XXI-26","side":"w","board":"bbbbbbbb.b.b...b.ww.w.w..wwwwwww","moves":"gf4 ba5 cb4 ac3 bd4 fg5"},
{"id":"XXII-1","side":"w","board":"bbb.bbbbbbbb...b..w.ww.wwwwwwwww","moves":"e3-f4 h8-g5"},
{"id":"XXII-2","side":"w","board":"bbbbbbbbbbwb....b...ww.wwwwwwwww","moves":"e3-f6 f6-b4"},
{"id":"XXII-3","side":"w","board":"bbbbbbbbbbb...bw....ww.wwwwwwwww","moves":"e3-g5 h6-e5"},
{"id":"XXII-4","side":"w","board":"bbbbbbbbbb.bb......www.wwwwwwwww","moves":"e3-h4 f6-a5"},
{"id":"XXII-5","side":"w","board":"bbbbbbb.bbbb...b...www.wwwwwwwww","moves":"e3-h4 g7-g5"},
{"id":"XXII-6","side":"w","board":"bbbbbbbbbbb.b......www.wwwwwwwww","moves":"e3-h4 h6-a5"},
{"id":"XXII-7","side":"w","board":"bbbbbbbbbbb....b...www.wwwwwwwww","moves":"e3-h4 h6-g5"},
{"id":"XXII-8","side":"w","board":"bbbbbbbbbbbwb.......ww.wwwwwwwww","moves":"e3-h6 h6-a5"},
{"id":"XXII-9","side":"w","board":"bbbbbbbbbbbw..b.....ww.wwwwwwwww","moves":"e3-h6 h6-e5"},
{"id":"XXII-10","side":"w","board":"bbbbbb.bbbbb.......bwwwwwwwwwwww","moves":"--- e7-h4"},
{"id":"XXII-11","side":"w","board":"b.bbbbbbbbbbw.....b.wwwwww.wwwww","moves":"f2-a5 d8-f4"},
{"id":"XXII-12","side":"w","board":"bbbbbbbbb.bbw.b.....wwwwww.wwwww","moves":"f2-a5 d6-e5"},
{"id":"XXII-13","side":"w","board":"bbbbbb.bbbbbw.b.....wwwwww.wwwww","moves":"f2-a5 e7-e5"},
{"id":"XXII-14","side":"w","board":"bbbbbbbbbb.bw.b.....wwwwww.wwwww","moves":"f2-a5 f6-e5"},
{"id":"XXII-15","side":"w","board":"bbbbbbb.bbbbw.b.....wwwwww.wwwww","moves":"f2-a5 g7-e5"},
{"id":"XXII-16","side":"w","board":"bbbbbbbbb.bbb...w...wwwwww.wwwww","moves":"f2-b4 d6-a5"},
{"id":"XXII-17","side":"w","board":"b.bbbbbbbbbb....w..bwwwwww.wwwww","moves":"f2-b4 d8-h4"},
{"id":"XXII-18","side":"w","board":"bbbbbb.bbbbb..b.w...wwwwww.wwwww","moves":"f2-b4 e7-e5"},
{"id":"XXII-19","side":"w","board":"bbbbbbb.bbbb..b.w...wwwwww.wwwww","moves":"f2-b4 g7-e5"},
{"id":"XXII-20","side":"w","board":"bbb.bbbbbbbb.b..w...wwwwww.wwwww","moves":"f2-b4 h8-c5"},
{"id":"XXII-21","side":"w","board":"bbb.bbbbbbbb...bw...wwwwww.wwwww","moves":"f2-b4 h8-g5"},
{"id":"XXII-22","side":"w","board":"bbbb.bbbbbbb.w......wwwwwwbwwwww","moves":"f2-c5 a7-f2"},
{"id":"XXII-23","side":"w","board":"bbb.bbbbbbbb.wb.....wwwwww.wwwww","moves":"f2-c5 h8-e5"},
{"id":"XXII-24","side":"w","board":"bbbbbbbb.bbb.b...w..wwwwww.wwwww","moves":"f2-d4 b6-c5"},
{"id":"XXII-25","side":"w","board":"bbbbb.bbbbbb...b.w..wwwwww.wwwww","moves":"f2-d4 c7-g5"},
{"id":"XXII-26","side":"w","board":"bbbbbbbbb.bbb....w..wwwwww.wwwww","moves":"f2-d4 d6-a5"},
{"id":"XXIII-1","side":"w","board":"bbbbbbbb..bb..b.w.w.w.w.w.wwwwww","moves":"gf4 ba5 cb4 ac3 db4 de5"},
{"id":"XXIII-2","side":"w","board":"bbbbbbbb.b.b...bw.w.w.w.w.wwwwww","moves":"gf4 ba5 cb4 ac3 db4 fg5"},
{"id":"XXIII-3","side":"w","board":"bbbbbbbb..bb..b..ww.w.w..wwwwwww","moves":"gf4 ba5 cb4 ac3 bd4 de5"},
{"id":"XXIII-4","side":"w","board":"bbbbbbbb.b.b...b.ww.w.w..wwwwwww","moves":"gf4 ba5 cb4 ac3 bd4 fg5"},
{"id":"XXIII-5","side":"w","board":"bbbb.bbbb.bbb.b...wwwww.www.wwww","moves":"gf4 ba5 hg3 ab6 gh4 de5"},
{"id":"XXIII-6","side":"w","board":"bbbbbbbb.b.bb..b..w.wwwwwww.wwww","moves":"gf4 ba5 hg3 fg5"},
{"id":"XXIII-7","side":"w","board":"bbbb.bbb.bbbbb....wwwww.www.wwww","moves":"gf4 bc5 hg3 ab6 gh4 ba5"},
{"id":"XXIII-8","side":"b","board":"bbbbbbbb.b.b.bb..ww.w.wwwww.wwww","moves":"gf4 bc5 hg3 fe5 cd4"},
{"id":"XXIII-9","side":"w","board":"bbbbbbbbb.bb.b....w.www.wwwwwwww","moves":"gf4 dc5"},
{"id":"XXIII-10","side":"w","board":"bbbbbbbb..bbbb..w.w.w.w.wwwwwwww","moves":"gf4 dc5 cb4 ba5"},
{"id":"XXIII-11","side":"w","board":"bbbbbbbbb..b.b.bw.w.w.w.wwwwwwww","moves":"gf4 dc5 cb4 fg5"},
{"id":"XXIII-12","side":"w","board":"bbbbbb.bbbbb.b...ww.w.w.wwwwwwww","moves":"gf4 dc5 cd4 ed6"},
{"id":"XXIII-13","side":"w","board":"bbbbbb.bbb.b.bb...wwwww.www.wwww","moves":"gf4 dc5 hg3 ed6 gh4 fe5"},
{"id":"XXIII-14","side":"w","board":"bbbbbbbbb.bb..b...w.www.wwwwwwww","moves":"gf4 de5"},
{"id":"XXIII-15","side":"w","board":".bbbbbbbb.bb..b.....wwwwww.wwwww","moves":"gf4 de5 fd6 ce5 fg3 bc7"},
{"id":"XXIII-16","side":"b","board":"bbbbb.bbb.bb..b.w....ww.wwwwwwww","moves":"gf4 de5 fd6 ce5 ab4"},
{"id":"XXIII-17","side":"b","board":"bbbbbb.bb.bb.b......wwwwwww.wwww","moves":"gf4 de5 fd6 ec5 hg3"},
{"id":"XXIII-18","side":"w","board":"bbbbbbbbbb.b..b...w.www.wwwwwwww","moves":"gf4 fe5"},
{"id":"XXIII-19","side":"w","board":"bbbbbbb.bbbb....w..w.ww.ww.wwwww","moves":"gf4 fe5 ab4 eg3 fh4 gf6"},
{"id":"XXIII-20","side":"w","board":"bbbbbbbbbb.b......w.wbw.wwwwwwww","moves":"gf4 fe5 cd4 ec3"},
{"id":"XXIII-21","side":"w","board":"bbbbbbbbbb.b.....w..w.wbwwwwwwww","moves":"gf4 fe5 cd4 eg3"},
{"id":"XXIII-22","side":"b","board":"bbbbbbbbbb.b..b..ww.ww..wwwwwwww","moves":"gf4 fe5 ed4"},
{"id":"XXIII-23","side":"w","board":"bbbbbbbb.b.bb....ww.ww..www.wwww","moves":"gf4 fe5 ed4 eg3 hf4 ba5"},
{"id":"XXIII-24","side":"b","board":"bbbbbbbbbb.b..b...w.wwwwww.wwwww","moves":"gf4 fe5 fg3"},
{"id":"XXIII-25","side":"b","board":"bbbbbb.bbbbb..b.w.w..wwwww.wwwww","moves":"gf4 fe5 fg3 ef6 ab4"},
{"id":"XXIII-26","side":"w","board":"bbbb.bbbbb.b.bb.w.w.w.wwwww.wwww","moves":"gf4 fe5 hg3 bc5 cb4 ab6"},
{"id":"XXIV-1","side":"w","board":"bbbbbbbbbbb....b.w..wwwwww.wwwww","moves":"f2-d4 h6-g5"},
{"id":"XXIV-2","side":"w","board":"bbbbbbbbb.bb..b...w.wwwwww.wwwww","moves":"f2-f4 d6-e5"},
{"id":"XXIV-3","side":"w","board":"bbbbbbbbbb.b..b...w.wwwwww.wwwww","moves":"f2-f4 f6-e5"},
{"id":"XXIV-4","side":"w","board":"bbbbbbbbbbb.b.....w.wwwwww.wwwww","moves":"f2-f4 h6-a5"},
{"id":"XXIV-5","side":"w","board":"bbb.bbbbbbbb..b...w.wwwwww.wwwww","moves":"f2-f4 h8-e5"},
{"id":"XXIV-6","side":"w","board":"bbbbbbb.bbbbb..w....wwwwww.wwwww","moves":"f2-g5 g7-a5"},
{"id":"XXIV-7","side":"w","board":"bbbbbbbbbbb.b..w....wwwwww.wwwww","moves":"f2-g5 h6-a5"},
{"id":"XXIV-8","side":"w","board":"bbbbbbbbbbb..b.w....wwwwww.wwwww","moves":"f2-g5 h6-c5"},
{"id":"XXIV-9","side":"w","board":"bbbbbbbbbbbb.......wwwwwww.wwwww","moves":"f2-h4 ---"},
{"id":"XXIV-10","side":"w","board":"bbbbbbbbbb.b.b.....wwwwwww.wwwww","moves":"f2-h4 f6-c5"},
{"id":"XXIV-11","side":"w","board":"bbbbbbbbbb.bb.......wwwwwwwwwwww","moves":"--- f6-a5"},
{"id":"XXIV-12","side":"w","board":"bbbbbbbbbb.b.......bwwwwwwwwwwww","moves":"--- f6-h4"},
{"id":"XXIV-13","side":"w","board":"bbbbbbbbbb.bw...b...wwwwwwwwwww.","moves":"g1-a5 f6-b4"},
{"id":"XXIV-14","side":"w","board":"bbbbbbb.bbbbwb......wwwwwwwwwww.","moves":"g1-a5 g7-c5"},
{"id":"XXIV-15","side":"w","board":"bbbbbbbbb.bb..b.w...wwwwwwwwwww.","moves":"g1-b4 d6-e5"},
{"id":"XXIV-16","side":"w","board":"bbbbbb.bbbbb.b..w...wwwwwwwwwww.","moves":"g1-b4 e7-c5"},
{"id":"XXIV-17","side":"w","board":"bbb.bbbbbbbb.b..w...wwwwwwwwwww.","moves":"g1-b4 h8-c5"},
{"id":"XXIV-18","side":"w","board":"bbbbbbbbb.bb...b.w..wwwwwwwwwww.","moves":"g1-d4 d6-g5"},
{"id":"XXIV-19","side":"w","board":"bbbbbbbbbbb.b....w..wwwwwwwwwww.","moves":"g1-d4 h6-a5"},
{"id":"XXIV-20","side":"w","board":"bbbbbbb.bbbbb.w.....wwwwwwwwwww.","moves":"g1-e5 g7-a5"},
{"id":"XXIV-21","side":"w","board":"bbbbbbbbb.bb.b....w.wwwwwwwwwww.","moves":"g1-f4 d6-c5"},
{"id":"XXIV-22","side":"w","board":"bbbbbbbbb.bb..b...w.wwwwwwwwwww.","moves":"g1-f4 d6-e5"},
{"id":"XXIV-23","side":"w","board":"bbb.bbbbbbbbb.....w.wwwwwwwwwww.","moves":"g1-f4 h8-a5"},
{"id":"XXIV-24","side":"w","board":"bbbbbbb.bbbbb..w....wwwwwwwwwww.","moves":"g1-g5 g7-a5"},
{"id":"XXIV-25","side":"w","board":"bbbbbbb.bbbb..bw....wwwwwwwwwww.","moves":"g1-g5 g7-e5"},
{"id":"XXIV-26","side":"w","board":"bbb.bbbbbbbbb..w....wwwwwwwwwww.","moves":"g1-g5 h8-a5"},
{"id":"XXV-1","side":"b","board":"bbbbbbbbbb.b.w....w.ww.wwww.wwww","moves":"gf4 fe5 hg3 ed4 ec5"},
{"id":"XXV-2","side":"b","board":"bbbbbb.bbbbb..b..ww.w.wwwww.wwww","moves":"gf4 fe5 hg3 ef6 cd4"},
{"id":"XXV-3","side":"b","board":"bbbbbbb.bbbb..b.w.w.w.wwwww.wwww","moves":"gf4 fe5 hg3 gf6 cb4"},
{"id":"XXV-4","side":"b","board":"bbbbbbb.bbbb..b..ww.ww.wwww.wwww","moves":"gf4 fe5 hg3 gf6 ed4"},
{"id":"XXV-5","side":"w","board":"bbbbbbbbb..b..bbw.w.w.w.wwwwwwww","moves":"gf4 fg5 cb4 de5"},
{"id":"XXV-6","side":"w","board":"bbbbbbb.b.bb..bbw.w.www..wwwwwww","moves":"gf4 fg5 cb4 gf6 bc3 de5"},
{"id":"XXV-7","side":"b","board":"bbbbbbbbbbbb.......wwww.wwwwwwww","moves":"gh4"},
{"id":"XXV-8","side":"w","board":"bbbbbbbb.bbbb......wwww.wwwwwwww","moves":"gh4 ba5"},
{"id":"XXV-9","side":"w","board":"bbbb.bbbbb.bb..b...wwwwwwwwwwww.","moves":"gh4 ba5 fg3 ab6 gf2 fg5"},
{"id":"XXV-10","side":"b","board":"bbbbbbbb..bbb.b..w.www.www.wwwww","moves":"gh4 ba5 fg3 de5 ed4"},
{"id":"XXV-11","side":"b","board":"bbbbbbbb.b.bb.b..w.www.www.wwwww","moves":"gh4 ba5 fg3 fe5 ed4"},
{"id":"XXV-12","side":"w","board":"bbbbbbbb.b.bb....wbwww.www.wwwww","moves":"gh4 ba5 fg3 fe5 ed4 ef4"},
{"id":"XXV-13","side":"b","board":"bbbbbbbb.bb.b..b...wwwwwwwwwwww.","moves":"gh4 ba5 fg3 hg5 gf2"},
{"id":"XXV-14","side":"b","board":"bbbbbbbb.b.bb.b..w.www.wwww.wwww","moves":"gh4 ba5 hg3 fe5 ed4"},
{"id":"XXV-15","side":"w","board":"bbbb.bbbb.bbbb....wwww.wwww.wwww","moves":"gh4 ba5 hg3 ab6 ef4 dc5"},
{"id":"XXV-16","side":"w","board":".bbbbbbbbbbbb......wwwwwwwwwwww.","moves":"gh4 ba5 hg3 ab6 gh2 ba7"},
{"id":"XXV-17","side":"w","board":"bbbbbbbb.bbb.b.....wwww.wwwwwwww","moves":"gh4 bc5"},
{"id":"XXV-18","side":"w","board":"bbbb.bbbbbbb.b...w.ww.w.wwwwwwww","moves":"gh4 bc5 cd4 ab6"},
{"id":"XXV-19","side":"w","board":"bbbbbbbb.b.b.bb..w.ww.w.wwwwwwww","moves":"gh4 bc5 cd4 fe5"},
{"id":"XXV-20","side":"w","board":"bbbbb.bbbbbb......wwww..w.wwwwww","moves":"gh4 bc5 ed4 ce3 df4 cb6"},
{"id":"XXV-21","side":"w","board":"bbbbbbbb..bb..b..w.www..ww.wwwww","moves":"gh4 bc5 ed4 ce3 fd4 de5"},
{"id":"XXV-22","side":"w","board":"bbbb.bbbbb.b.b.b.w.ww.wwww.wwwww","moves":"gh4 bc5 fg3 ab6 cd4 fg5"},
{"id":"XXV-23","side":"w","board":"bbbbbbbbb.bb.b.....wwww.wwwwwwww","moves":"gh4 dc5"},
{"id":"XXV-24","side":"w","board":"bbbbbbbbb.bb....wb.ww.w.wwwwwwww","moves":"gh4 dc5 cb4 cd4"},
{"id":"XXV-25","side":"w","board":"bbbbbbbbb..b.b.bw..ww.w.wwwwwwww","moves":"gh4 dc5 cb4 fg5"},
{"id":"XXV-26","side":"w","board":"bbbbb.bbbbbb.b....wwww..wwwwwwww","moves":"gh4 dc5 ef4 cd6"},
{"id":"XXVI-1","side":"w","board":"bbbbbbbbb.bb.b.....wwwwwwwwwwww.","moves":"g1-h4 d6-c5"},
{"id":"XXVI-2","side":"w","board":"bbbbbb.bbbbb...b...wwwwwwwwwwww.","moves":"g1-h4 e7-g5"},
{"id":"XXVI-3","side":"w","board":"bbbbbbbbbbb....b...wwwwwwwwwwww.","moves":"g1-h4 h6-g5"},
{"id":"XXVI-4","side":"w","board":"bbbbbbbbbbbbw.......www.wwwwwwww","moves":"g3-a5 ---"},
{"id":"XXVI-5","side":"w","board":"bbbb.bbbbbbbw.b.....www.wwwwwwww","moves":"g3-a5 a7-e5"},
{"id":"XXVI-6","side":"w","board":"bbbbbbbb.bbbw.b.....www.wwwwwwww","moves":"g3-a5 b6-e5"},
{"id":"XXVI-7","side":"w","board":"bbbbbbbbbbb.w..b....www.wwwwwwww","moves":"g3-a5 h6-g5"},
{"id":"XXVI-8","side":"w","board":"bbbb.bbbbbbb..b.w...www.wwwwwwww","moves":"g3-b4 a7-e5"},
{"id":"XXVI-9","side":"w","board":"bbbbbbbb.bbb..b.w...www.wwwwwwww","moves":"g3-b4 b6-e5"},
{"id":"XXVI-10","side":"w","board":"bb.bbbbbbbbb....w.b.www.wwwwwwww","moves":"g3-b4 f8-f4"},
{"id":"XXVI-11","side":"w","board":"bbbbbbb.bbbb...bw...www.wwwwwwww","moves":"g3-b4 g7-g5"},
{"id":"XXVI-12","side":"w","board":"bbb.bbbbbbbb....w..bwww.wwwwwwww","moves":"g3-b4 h8-h4"},
{"id":"XXVI-13","side":"w","board":"bbbbbbbbbbb....bw...www.wwwwwwww","moves":"g3-b4 h6-g5"},
{"id":"XXVI-14","side":"w","board":"bbbbbbbb.bbb.w.b....www.wwwwwwww","moves":"g3-c5 b6-g5"},
{"id":"XXVI-15","side":"w","board":"bbbb.bbbbbbbb....w..www.wwwwwwww","moves":"g3-d4 a7-a5"},
{"id":"XXVI-16","side":"w","board":"bbbb.bbbbbbb..b..w..www.wwwwwwww","moves":"g3-d4 a7-e5"},
{"id":"XXVI-17","side":"w","board":"bbbb.bbbbbbb.....wb.www.wwwwwwww","moves":"g3-d4 a7-f4"},
{"id":"XXVI-18","side":"w","board":"bbbbbbbb.bbb.b...w..www.wwwwwwww","moves":"g3-d4 b6-c5"},
{"id":"XXVI-19","side":"w","board":"bbbbbbbbb.bbb....w..www.wwwwwwww","moves":"g3-d4 d6-a5"},
{"id":"XXVI-20","side":"w","board":"bbbbbbbbb.bb..b..w..www.wwwwwwww","moves":"g3-d4 d6-e5"},
{"id":"XXVI-21","side":"w","board":"bbbbbbb.bbbbb....w..www.wwwwwwww","moves":"g3-d4 g7-a5"},
{"id":"XXVI-22","side":"w","board":"bbbbbbb.bbbb..w....bwww.wwwwwwww","moves":"g3-e5 g7-h4"},
{"id":"XXVI-23","side":"w","board":"bbb.bbbbbbbbb.w.....www.wwwwwwww","moves":"g3-e5 h8-a5"},
{"id":"XXVI-24","side":"w","board":"bbbbbbbbbbbb......w.www.wwwwwwww","moves":"g3-f4 ---"},
{"id":"XXVI-25","side":"w","board":"bbbbbbbbb.bb...b..w.www.wwwwwwww","moves":"g3-f4 d6-g5"},
{"id":"XXVI-26","side":"w","board":"bbbbbbb.bbbbb.....w.www.wwwwwwww","moves":"g3-f4 g7-a5"},
{"id":"XXVII-1","side":"b","board":"bbbbbbbbb..b.bb..w.ww.wwww.wwwww","moves":"gh4 dc5 fg3 fe5 cd4"},
{"id":"XXVII-2","side":"b","board":"bbbbbbbbb..b.bb..w.www.www.wwwww","moves":"gh4 dc5 fg3 fe5 ed4"},
{"id":"XXVII-3","side":"w","board":"bbbbbbbbb..b.bb....wwwwwwww.wwww","moves":"gh4 dc5 hg3 fe5"},
{"id":"XXVII-4","side":"w","board":"bbbbbbbbb.bb..b....wwww.wwwwwwww","moves":"gh4 de5"},
{"id":"XXVII-5","side":"w","board":"bbbbb.bbbbbb..b.w..w.ww.wwwwwwww","moves":"gh4 de5 ab4 cd6"},
{"id":"XXVII-6","side":"b","board":"bbbbbbbbb.bb..b....wwwwwww.wwwww","moves":"gh4 de5 fg3"},
{"id":"XXVII-7","side":"w","board":"bbbbbbbb..bb.bb....wwwwwwww.wwww","moves":"gh4 de5 hg3 bc5"},
{"id":"XXVII-8","side":"w","board":"bbbbbbbbbb.b..b....wwww.wwwwwwww","moves":"gh4 fe5"},
{"id":"XXVII-9","side":"w","board":"bbbbbbbbbb.b....wb.w.ww.wwwwwwww","moves":"gh4 fe5 ab4 ed4"},
{"id":"XXVII-10","side":"w","board":"bbbbbbbbbb.b....w.bww.w.wwwwwwww","moves":"gh4 fe5 cb4 ef4"},
{"id":"XXVII-11","side":"w","board":"bbbbbbbb.b.bb....w.ww.w..wwwwwww","moves":"gh4 fe5 cd4 ec3 bd4 ba5"},
{"id":"XXVII-12","side":"w","board":"bbbbbbbb.b.b.bb..w.www..wwwwwwww","moves":"gh4 fe5 ed4 bc5"},
{"id":"XXVII-13","side":"w","board":"bbbbbbbbb..b.bb..w.www..wwwwwwww","moves":"gh4 fe5 ed4 dc5"},
{"id":"XXVII-14","side":"w","board":"bbbbbb.bbbbb..b..w.www..wwwwwwww","moves":"gh4 fe5 ed4 ef6"},
{"id":"XXVII-15","side":"w","board":"bbbbbbb.bbbb..b..w.www..wwwwwwww","moves":"gh4 fe5 ed4 gf6"},
{"id":"XXVII-16","side":"w","board":"bbbbbbb.b.bb.bb..w.www.www.wwwww","moves":"gh4 fe5 ed4 gf6 fg3 dc5"},
{"id":"XXVII-17","side":"w","board":"bbbbbbbb.b.bb.....wwww..www.wwww","moves":"gh4 fe5 ef4 eg3 hf4 ba5"},
{"id":"XXVII-18","side":"b","board":"bbbbbbbbbb.b..b....wwwwwww.wwwww","moves":"gh4 fe5 fg3"},
{"id":"XXVII-19","side":"w","board":"bbbbbbb.bbbb..b....wwwwwww.wwwww","moves":"gh4 fe5 fg3 gf6"},
{"id":"XXVII-20","side":"w","board":"bbbbbbbbbb.b...b...wwww.wwwwwwww","moves":"gh4 fg5"},
{"id":"XXVII-21","side":"w","board":"bb.bbbbbbb.b..b.w....ww.wwwwwwww","moves":"gh4 fg5 hf6 ge5 ab4 fg7"},
{"id":"XXVII-22","side":"w","board":"bb.bbbbbbb.b..b..w..ww..wwwwwwww","moves":"gh4 fg5 hf6 ge5 ed4 fg7"},
{"id":"XXVII-23","side":"b","board":"bbbbbb.bbb.b...b.w..ww..wwwwwwww","moves":"gh4 fg5 hf6 eg5 ed4"},
{"id":"XXVII-24","side":"w","board":"bbbbbbbbb.b..b.b.w.ww.w.wwwwwwww","moves":"gh4 hg5 cd4 dc5"},
{"id":"XXVII-25","side":"b","board":"bbbbbbb.bbbb...b.w.ww.wwww.wwwww","moves":"gh4 hg5 cd4 gh6 fg3"},
{"id":"XXVII-26","side":"w","board":"bbbbbbbb.bb.b.....wwww..w.wwwwww","moves":"gh4 hg5 ef4 ge3 df4 ba5"},
{"id":"XXVIII-1","side":"w","board":"bbb.bbbbbbbb...b..w.www.wwwwwwww","moves":"g3-f4 h8-g5"},
{"id":"XXVIII-2","side":"w","board":"bbbb.bbbbbbb...w...bwww.wwwwwwww","moves":"g3-g5 a7-h4"},
{"id":"XXVIII-3","side":"w","board":"bbb.bbbbbbbb...wb...www.wwwwwwww","moves":"g3-g5 h8-b4"},
{"id":"XXVIII-4","side":"w","board":"bbbbbbbbbbb.b..w....www.wwwwwwww","moves":"g3-g5 h6-a5"},
{"id":"XXVIII-5","side":"w","board":"bbbbbbbbbbbb.......wwww.wwwwwwww","moves":"g3-h4 ---"},
{"id":"XXVIII-6","side":"w","board":"bbbb.bbbbbbb...b...wwww.wwwwwwww","moves":"g3-h4 a7-g5"},
{"id":"XXVIII-7","side":"w","board":"bbbbb.bbbbbb......bwwww.wwwwwwww","moves":"g3-h4 c7-f4"},
{"id":"XXVIII-8","side":"w","board":"bbbbbbb.bbbbb......wwww.wwwwwwww","moves":"g3-h4 g7-a5"},
{"id":"XXVIII-9","side":"w","board":"bbbbbbb.bbbb.b.....wwww.wwwwwwww","moves":"g3-h4 g7-c5"},
{"id":"XXVIII-10","side":"w","board":"bbb.bbbbbbbb..b....wwww.wwwwwwww","moves":"g3-h4 h8-e5"},
{"id":"XXVIII-11","side":"w","board":"bbbbbbbbbbbwb.......www.wwwwwwww","moves":"g3-h6 h6-a5"},
{"id":"XXVIII-12","side":"w","board":"bbbbbbbbbbbw..b.....www.wwwwwwww","moves":"g3-h6 h6-e5"},
{"id":"XXVIII-13","side":"w","board":"bbbbbbbbbbbw.......bwww.wwwwwwww","moves":"g3-h6 h6-h4"},
{"id":"XXVIII-14","side":"w","board":"bbbbbbb.bbbbb.......wwwwwwwwwwww","moves":"--- g7-a5"},
{"id":"XXVIII-15","side":"w","board":"bbbbbbb.bbbb..b.....wwwwwwwwwwww","moves":"--- g7-e5"},
{"id":"XXVIII-16","side":"w","board":"bbbbbbb.bbbb...b....wwwwwwwwwwww","moves":"--- g7-g5"},
{"id":"XXVIII-17","side":"w","board":"bbbbbbb.bbbb.......bwwwwwwwwwwww","moves":"--- g7-h4"},
{"id":"XXVIII-18","side":"w","board":"bbbbbbbbbbbbw.......wwwwwww.wwww","moves":"h2-a5 ---"},
{"id":"XXVIII-19","side":"w","board":"bbbb.bbbbbbbw..b....wwwwwww.wwww","moves":"h2-a5 a7-g5"},
{"id":"XXVIII-20","side":"w","board":"bbbb.bbbbbbbw.......wwwwwwwbwwww","moves":"h2-a5 a7-h2"},
{"id":"XXVIII-21","side":"w","board":"bbbbbbbb.bbbw.......wwwwwwwbwwww","moves":"h2-a5 b6-h2"},
{"id":"XXVIII-22","side":"w","board":"bbbbbbbbb.bbw.......wwwwwwwbwwww","moves":"h2-a5 d6-h2"},
{"id":"XXVIII-23","side":"w","board":"bbbbbb.bbbbbw..b....wwwwwww.wwww","moves":"h2-a5 e7-g5"},
{"id":"XXVIII-24","side":"w","board":"bbbbbbbbbb.bw......bwwwwwww.wwww","moves":"h2-a5 f6-h4"},
{"id":"XXVIII-25","side":"w","board":"bbbbbbb.bbbbw...b...wwwwwww.wwww","moves":"h2-a5 g7-b4"},
{"id":"XXVIII-26","side":"w","board":"bbbbbbb.bbbbw.......wwwwwwwbwwww","moves":"h2-a5 g7-h2"},
{"id":"XXIX-1","side":"w","board":"bbbbbbbb.bb..b....wwww..w.wwwwww","moves":"gh4 hg5 ef4 ge3 df4 bc5"},
{"id":"XXIX-2","side":"w","board":"bbbbbbbbb.b...bb...wwwwwwww.wwww","moves":"gh4 hg5 hg3 de5"},
{"id":"XXIX-3","side":"w","board":"bbbbbbb.bbbb...b...wwwwwwww.wwww","moves":"gh4 hg5 hg3 gh6"},
{"id":"XXIX-4","side":"w","board":"bbbb.bbbbbbb...bw...wwwwwww.wwww","moves":"h2-b4 a7-g5"},
{"id":"XXIX-5","side":"w","board":"bbbb.bbbbbbb....w...wwwwwwwbwwww","moves":"h2-b4 a7-h2"},
{"id":"XXIX-6","side":"w","board":"bbb.bbbbbbbbw.......wwwwwwwbwwww","moves":"h2-a5 h8-h2"},
{"id":"XXIX-7","side":"w","board":"bbb.bbbbbbbbw......bwwwwwww.wwww","moves":"h2-a5 h8-h4"},
{"id":"XXIX-8","side":"w","board":"bbbbwbbbbbbb.....b..wwwwwww.wwww","moves":"h2-a7 a7-d4"},
{"id":"XXIX-9","side":"w","board":"bbbb.bbbbbbb..b.w...wwwwwww.wwww","moves":"h2-b4 a7-e5"},
{"id":"XXIX-10","side":"w","board":"bbbbbbbb.bbb.b..w...wwwwwww.wwww","moves":"h2-b4 b6-c5"},
{"id":"XXIX-11","side":"w","board":"bbbbbbbb.bbb....w...wwwwwwwbwwww","moves":"h2-b4 b6-h2"},
{"id":"XXIX-12","side":"w","board":"bbbbbbbbb.bb...bw...wwwwwww.wwww","moves":"h2-b4 d6-g5"},
{"id":"XXIX-13","side":"w","board":"bbbbbbbbb.bb....w...wwwwwwwbwwww","moves":"h2-b4 d6-h2"},
{"id":"XXIX-14","side":"w","board":"bbbbbbb.bbbb....w...wwwwwwwbwwww","moves":"h2-b4 g7-h2"},
{"id":"XXIX-15","side":"w","board":"bbb.bbbbbbbb....w...wwwwwwwbwwww","moves":"h2-b4 h8-h2"},
{"id":"XXIX-16","side":"w","board":"bbbb.bbbbbbb.w....b.wwwwwww.wwww","moves":"h2-c5 a7-f4"},
{"id":"XXIX-17","side":"w","board":"bbbb.bbbbbbb.w......wwwwwwwbwwww","moves":"h2-c5 a7-h2"},
{"id":"XXIX-18","side":"w","board":"bbbbbbbb.bbb.w......wwwwwwwbwwww","moves":"h2-c5 b6-h2"},
{"id":"XXIX-19","side":"w","board":"bbbbbbbbb.bb.w......wwwwwwwbwwww","moves":"h2-c5 d6-h2"},
{"id":"XXIX-20","side":"w","board":"bbbbbbbbbb.b.w......wwwwwwwbwwww","moves":"h2-c5 f6-h2"},
{"id":"XXIX-21","side":"w","board":"bbb.bbbbbbbb.w......wwwwwwwbwwww","moves":"h2-c5 h8-h2"},
{"id":"XXIX-22","side":"w","board":"bbbb.bbbbbbb.....w..wwwwwwwbwwww","moves":"h2-d4 a7-h2"},
{"id":"XXIX-23","side":"w","board":"bbbbbbbb.bbb.b...w..wwwwwww.wwww","moves":"h2-d4 b6-c5"},
{"id":"XXIX-24","side":"w","board":"bbbbbbbb.bbb.....w..wwwwwwwbwwww","moves":"h2-d4 b6-h2"},
{"id":"XXIX-25","side":"w","board":"bbbbb.bbbbbb.....w..wwwwwwwbwwww","moves":"h2-d4 c7-h2"},
{"id":"XXIX-26","side":"w","board":"bbbbbbbbb.bb.....w..wwwwwwwbwwww","moves":"h2-d4 d6-h2"},
{"id":"XXX-1","side":"w","board":"bbbbbbb.bbbb.....w..wwwwwwwbwwww","moves":"h2-d4 g7-h2"},
{"id":"XXX-2","side":"w","board":"bbbb.bbbbbbb..w.b...wwwwwww.wwww","moves":"h2-e5 a7-b4"},
{"id":"XXX-3","side":"w","board":"bbbb.bbbbbbb..w..b..wwwwwww.wwww","moves":"h2-e5 a7-d4"},
{"id":"XXX-4","side":"w","board":"bbbbbb.bbbbb..w.....wwwwwwwbwwww","moves":"h2-e5 e7-h2"},
{"id":"XXX-5","side":"w","board":"bbb.bbbbbbbb..w.....wwwwwwwbwwww","moves":"h2-e5 h8-h2"},
{"id":"XXX-6","side":"w","board":"bbbbbbbbbbbb......w.wwwwwww.wwww","moves":"h2-f4 ---"},
{"id":"XXX-7","side":"w","board":"bbbb.bbbbbbb......w.wwwwwwwbwwww","moves":"h2-f4 a7-h2"},
{"id":"XXX-8","side":"w","board":"bbbbb.bbbbbb......wbwwwwwww.wwww","moves":"h2-f4 c7-h4"},
{"id":"XXX-9","side":"w","board":"bbbbb.bbbbbb......w.wwwwwwwbwwww","moves":"h2-f4 c7-h2"},
{"id":"XXX-10","side":"w","board":"bbbbbb.bbbbb......w.wwwwwwwbwwww","moves":"h2-f4 e7-h2"},
{"id":"XXX-11","side":"w","board":"bbbbbbbbbb.b..b...w.wwwwwww.wwww","moves":"h2-f4 f6-e5"},
{"id":"XXX-12","side":"w","board":"bbbbbbbbbbb..b....w.wwwwwww.wwww","moves":"h2-f4 h6-c5"},
{"id":"XXX-13","side":"w","board":"bbbbb.bbbbbbb..w....wwwwwww.wwww","moves":"h2-g5 c7-a5"},
{"id":"XXX-14","side":"w","board":"bbbbb.bbbbbb..bw....wwwwwww.wwww","moves":"h2-g5 c7-e5"},
{"id":"XXX-15","side":"w","board":"bbbbbbbbb.bb...w....wwwwwwwbwwww","moves":"h2-g5 d6-h2"},
{"id":"XXX-16","side":"w","board":"bbbbbbbbbbbb.......wwwwwwww.wwww","moves":"h2-h4 ---"},
{"id":"XXX-17","side":"w","board":"bbbbbbbbbbb........wwwwwwwwbwwww","moves":"h2-h4 h6-h2"},
{"id":"XXX-18","side":"w","board":"bbbb.bbbbbbb..b....wwwwwwww.wwww","moves":"h2-h4 a7-e5"},
{"id":"XXX-19","side":"w","board":"bbbb.bbbbbbb.......wwwwwwwwbwwww","moves":"h2-h4 a7-h2"},
{"id":"XXX-20","side":"w","board":"bbbbbbbbb.bb..b....wwwwwwww.wwww","moves":"h2-h4 d6-e5"},
{"id":"XXX-21","side":"w","board":"bbbbbbbbbbbw......b.wwwwwww.wwww","moves":"h2-h6 h6-f4"},
{"id":"XXX-22","side":"w","board":"bbbbbbbbbbbw.......bwwwwwww.wwww","moves":"h2-h6 h6-h4"},
{"id":"XXX-23","side":"w","board":"bbbbbbbbbbb.......b.wwwwwwwwwwww","moves":"--- h6-f4"},
{"id":"XXX-24","side":"w","board":"bbbbbbbbbbb........bwwwwwwwwwwww","moves":"--- h6-h4"},
{"id":"XXX-25","side":"w","board":"bbb.bbbbbbbb...b....wwwwwwwwwwww","moves":"--- h8-g5"},
{"id":"XXX-26","side":"w","board":"bbb.bbbbbbbb.......bwwwwwwwwwwww","moves":"--- h8-h4"}];
if (typeof module!=='undefined') module.exports=IDF780; else window.IDF780=IDF780;
